package generators

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/supabase/postgres-meta/cli/pkg/pgmeta"
)

// DjangoGenerator generates Django model definitions
type DjangoGenerator struct{}

// Name returns the generator name
func (g *DjangoGenerator) Name() string {
	return "django"
}

// Generate generates Django model definitions from the metadata
func (g *DjangoGenerator) Generate(meta *pgmeta.GeneratorMetadata, opts Options) (string, error) {
	ctx := newDjangoContext(meta)
	return ctx.generate()
}

// djangoContext holds the context for Django generation
type djangoContext struct {
	meta        *pgmeta.GeneratorMetadata
	types       map[string]pgmeta.PostgresType
	userEnums   map[string][]string
	columns     map[int64][]pgmeta.PostgresColumn
	schemas     map[string]pgmeta.PostgresSchema
	schemaNames map[string]bool
	primaryKeys map[int64][]string // tableID -> primary key column names
	foreignKeys map[int64][]pgmeta.PostgresRelationship
}

func newDjangoContext(meta *pgmeta.GeneratorMetadata) *djangoContext {
	ctx := &djangoContext{
		meta:        meta,
		types:       make(map[string]pgmeta.PostgresType),
		userEnums:   make(map[string][]string),
		columns:     make(map[int64][]pgmeta.PostgresColumn),
		schemas:     make(map[string]pgmeta.PostgresSchema),
		schemaNames: make(map[string]bool),
		primaryKeys: make(map[int64][]string),
		foreignKeys: make(map[int64][]pgmeta.PostgresRelationship),
	}

	// Build indexes
	for _, schema := range meta.Schemas {
		ctx.schemas[schema.Name] = schema
		ctx.schemaNames[schema.Name] = true
	}

	for _, t := range meta.Types {
		ctx.types[t.Name] = t
		if len(t.Enums) > 0 {
			ctx.userEnums[t.Schema+"."+t.Name] = t.Enums
		}
	}

	// Sort and group columns by table_id
	sortedColumns := make([]pgmeta.PostgresColumn, len(meta.Columns))
	copy(sortedColumns, meta.Columns)
	sort.Slice(sortedColumns, func(i, j int) bool {
		return sortedColumns[i].Name < sortedColumns[j].Name
	})

	for _, col := range sortedColumns {
		ctx.columns[col.TableID] = append(ctx.columns[col.TableID], col)
	}

	// Build primary key index
	for _, table := range meta.Tables {
		for _, pk := range table.PrimaryKeys {
			ctx.primaryKeys[table.ID] = append(ctx.primaryKeys[table.ID], pk.Name)
		}
	}

	// Build foreign key index
	for _, rel := range meta.Relationships {
		// Find the table ID for this relationship
		for _, table := range meta.Tables {
			if table.Schema == rel.Schema && table.Name == rel.Relation {
				ctx.foreignKeys[table.ID] = append(ctx.foreignKeys[table.ID], rel)
				break
			}
		}
	}

	return ctx
}

func (ctx *djangoContext) generate() (string, error) {
	var sb strings.Builder

	sb.WriteString(`# Generated by pg-meta
# Django model definitions

from django.db import models

`)

	// Generate TextChoices for enums
	for _, t := range ctx.meta.Types {
		if len(t.Enums) > 0 && ctx.schemaNames[t.Schema] {
			sb.WriteString(ctx.generateEnum(t))
			sb.WriteString("\n\n")
		}
	}

	// Generate models for tables
	for _, table := range ctx.meta.Tables {
		if !ctx.schemaNames[table.Schema] {
			continue
		}
		sb.WriteString(ctx.generateModel(table))
		sb.WriteString("\n\n")
	}

	// Generate models for views (as unmanaged models)
	for _, view := range ctx.meta.Views {
		if !ctx.schemaNames[view.Schema] {
			continue
		}
		sb.WriteString(ctx.generateViewModel(view))
		sb.WriteString("\n\n")
	}

	// Generate models for materialized views (as unmanaged models)
	for _, matview := range ctx.meta.MaterializedViews {
		if !ctx.schemaNames[matview.Schema] {
			continue
		}
		sb.WriteString(ctx.generateMaterializedViewModel(matview))
		sb.WriteString("\n\n")
	}

	return strings.TrimRight(sb.String(), "\n") + "\n", nil
}

func (ctx *djangoContext) generateEnum(t pgmeta.PostgresType) string {
	var sb strings.Builder
	className := toDjangoClassName(t.Name)

	sb.WriteString(fmt.Sprintf("class %s(models.TextChoices):\n", className))
	for _, v := range t.Enums {
		constName := toConstantName(v)
		sb.WriteString(fmt.Sprintf("    %s = '%s', '%s'\n", constName, v, v))
	}

	return strings.TrimRight(sb.String(), "\n")
}

func (ctx *djangoContext) generateModel(table pgmeta.PostgresTable) string {
	var sb strings.Builder
	className := toDjangoClassName(table.Name)
	cols := ctx.columns[table.ID]
	pks := ctx.primaryKeys[table.ID]
	fks := ctx.foreignKeys[table.ID]

	// Build FK lookup map: column name -> relationship
	fkMap := make(map[string]pgmeta.PostgresRelationship)
	for _, fk := range fks {
		for _, col := range fk.Columns {
			fkMap[col] = fk
		}
	}

	sb.WriteString(fmt.Sprintf("class %s(models.Model):\n", className))

	if len(cols) == 0 {
		sb.WriteString("    pass\n")
	} else {
		for _, col := range cols {
			// Skip if this is a FK column - we'll generate ForeignKey instead
			if fkRel, isFk := fkMap[col.Name]; isFk {
				sb.WriteString(ctx.generateForeignKeyField(col, fkRel, pks))
				sb.WriteString("\n")
				continue
			}

			field := ctx.columnToField(col, pks)
			sb.WriteString(fmt.Sprintf("    %s\n", field))
		}
	}

	// Add Meta class
	sb.WriteString("\n    class Meta:\n")
	if table.Schema != "public" {
		sb.WriteString(fmt.Sprintf("        db_table = '%s\".\"'%s'\n", table.Schema, table.Name))
	} else {
		sb.WriteString(fmt.Sprintf("        db_table = '%s'\n", table.Name))
	}

	return strings.TrimRight(sb.String(), "\n")
}

func (ctx *djangoContext) generateViewModel(view pgmeta.PostgresView) string {
	var sb strings.Builder
	className := toDjangoClassName(view.Name)
	cols := ctx.columns[view.ID]

	sb.WriteString(fmt.Sprintf("class %s(models.Model):\n", className))

	if len(cols) == 0 {
		sb.WriteString("    pass\n")
	} else {
		for _, col := range cols {
			field := ctx.columnToField(col, nil)
			sb.WriteString(fmt.Sprintf("    %s\n", field))
		}
	}

	// Add Meta class for unmanaged model
	sb.WriteString("\n    class Meta:\n")
	sb.WriteString("        managed = False\n")
	if view.Schema != "public" {
		sb.WriteString(fmt.Sprintf("        db_table = '%s\".\"'%s'\n", view.Schema, view.Name))
	} else {
		sb.WriteString(fmt.Sprintf("        db_table = '%s'\n", view.Name))
	}

	return strings.TrimRight(sb.String(), "\n")
}

func (ctx *djangoContext) generateMaterializedViewModel(matview pgmeta.PostgresMaterializedView) string {
	var sb strings.Builder
	className := toDjangoClassName(matview.Name)
	cols := ctx.columns[matview.ID]

	sb.WriteString(fmt.Sprintf("class %s(models.Model):\n", className))

	if len(cols) == 0 {
		sb.WriteString("    pass\n")
	} else {
		for _, col := range cols {
			field := ctx.columnToField(col, nil)
			sb.WriteString(fmt.Sprintf("    %s\n", field))
		}
	}

	// Add Meta class for unmanaged model
	sb.WriteString("\n    class Meta:\n")
	sb.WriteString("        managed = False\n")
	if matview.Schema != "public" {
		sb.WriteString(fmt.Sprintf("        db_table = '%s\".\"'%s'\n", matview.Schema, matview.Name))
	} else {
		sb.WriteString(fmt.Sprintf("        db_table = '%s'\n", matview.Name))
	}

	return strings.TrimRight(sb.String(), "\n")
}

func (ctx *djangoContext) generateForeignKeyField(col pgmeta.PostgresColumn, rel pgmeta.PostgresRelationship, pks []string) string {
	fieldName := toSnakeCase(strings.TrimSuffix(col.Name, "_id"))
	if fieldName == col.Name {
		fieldName = toSnakeCase(col.Name)
	}
	relatedModel := toDjangoClassName(rel.ReferencedRelation)

	opts := []string{
		fmt.Sprintf("'%s'", relatedModel),
		"on_delete=models.CASCADE",
		fmt.Sprintf("db_column='%s'", col.Name),
	}

	if col.IsNullable {
		opts = append(opts, "null=True", "blank=True")
	}

	// Check if this is part of primary key
	isPK := false
	for _, pk := range pks {
		if pk == col.Name {
			isPK = true
			break
		}
	}
	if isPK {
		opts = append(opts, "primary_key=True")
	}

	return fmt.Sprintf("    %s = models.ForeignKey(%s)", fieldName, strings.Join(opts, ", "))
}

func (ctx *djangoContext) columnToField(col pgmeta.PostgresColumn, pks []string) string {
	fieldName := toSnakeCase(col.Name)
	fieldType, fieldOpts := ctx.pgTypeToDjangoField(col)

	// Check if this is the primary key
	isPK := false
	for _, pk := range pks {
		if pk == col.Name {
			isPK = true
			break
		}
	}

	opts := []string{}

	// Handle primary key
	if isPK && col.IsIdentity {
		// Auto-incrementing primary key
		if fieldType == "models.BigIntegerField" {
			fieldType = "models.BigAutoField"
		} else {
			fieldType = "models.AutoField"
		}
		opts = append(opts, "primary_key=True")
	} else if isPK {
		opts = append(opts, "primary_key=True")
	}

	// Add db_column if name differs
	if fieldName != col.Name {
		opts = append(opts, fmt.Sprintf("db_column='%s'", col.Name))
	}

	// Handle nullable
	if col.IsNullable && !isPK {
		opts = append(opts, "null=True", "blank=True")
	}

	// Handle default value
	if col.DefaultValue != nil && !col.IsIdentity {
		// Skip complex defaults, just mark as having a default
		opts = append(opts, "default=None")
	}

	// Add field-specific options
	opts = append(opts, fieldOpts...)

	if len(opts) > 0 {
		return fmt.Sprintf("%s = %s(%s)", fieldName, fieldType, strings.Join(opts, ", "))
	}
	return fmt.Sprintf("%s = %s()", fieldName, fieldType)
}

func (ctx *djangoContext) pgTypeToDjangoField(col pgmeta.PostgresColumn) (string, []string) {
	format := col.Format
	opts := []string{}

	// Check if it's an array type
	if strings.HasPrefix(format, "_") {
		return "models.JSONField", opts
	}

	// Check if it's an enum
	if _, ok := ctx.userEnums[col.Schema+"."+format]; ok {
		enumClass := toDjangoClassName(format)
		opts = append(opts, fmt.Sprintf("max_length=255, choices=%s.choices", enumClass))
		return "models.CharField", opts
	}

	// Map PostgreSQL types to Django fields
	switch format {
	// Boolean
	case "bool":
		return "models.BooleanField", opts

	// Integer types
	case "int2":
		return "models.SmallIntegerField", opts
	case "int4":
		return "models.IntegerField", opts
	case "int8":
		return "models.BigIntegerField", opts

	// Floating point
	case "float4", "float8":
		return "models.FloatField", opts
	case "numeric":
		opts = append(opts, "max_digits=65", "decimal_places=30")
		return "models.DecimalField", opts

	// String types
	case "varchar", "bpchar":
		opts = append(opts, "max_length=255")
		return "models.CharField", opts
	case "text", "citext":
		return "models.TextField", opts

	// Date/Time types
	case "date":
		return "models.DateField", opts
	case "time", "timetz":
		return "models.TimeField", opts
	case "timestamp", "timestamptz":
		return "models.DateTimeField", opts

	// UUID
	case "uuid":
		return "models.UUIDField", opts

	// JSON types
	case "json", "jsonb":
		return "models.JSONField", opts

	// Binary
	case "bytea":
		return "models.BinaryField", opts

	// Network types
	case "inet":
		return "models.GenericIPAddressField", opts

	// Range types
	case "int4range":
		return "models.IntegerRangeField", opts
	case "int8range":
		return "models.BigIntegerRangeField", opts
	case "numrange":
		return "models.DecimalRangeField", opts
	case "tsrange", "tstzrange":
		return "models.DateTimeRangeField", opts
	case "daterange":
		return "models.DateRangeField", opts

	default:
		// For unknown types, use TextField
		return "models.TextField", opts
	}
}

// Helper functions

var djangoNonAlphanumericRegex = regexp.MustCompile(`[^a-zA-Z0-9]+`)

func toDjangoClassName(name string) string {
	parts := djangoNonAlphanumericRegex.Split(name, -1)
	var result strings.Builder
	for _, part := range parts {
		if len(part) > 0 {
			result.WriteString(strings.ToUpper(part[:1]))
			if len(part) > 1 {
				result.WriteString(part[1:])
			}
		}
	}
	return result.String()
}

func toSnakeCase(name string) string {
	// Convert camelCase to snake_case if needed, otherwise just lowercase
	var result strings.Builder
	for i, r := range name {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteRune('_')
			}
			result.WriteRune(r + 32) // lowercase
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func toConstantName(name string) string {
	// Convert to UPPER_SNAKE_CASE
	result := strings.ToUpper(name)
	result = djangoNonAlphanumericRegex.ReplaceAllString(result, "_")
	return result
}
