package generators

import (
	"fmt"
	"sort"
	"strings"

	"github.com/supabase/postgres-meta/cli/pkg/pgmeta"
)

// DrizzleGenerator generates Drizzle ORM schema definitions
type DrizzleGenerator struct{}

// Name returns the generator name
func (g *DrizzleGenerator) Name() string {
	return "drizzle"
}

// Generate generates Drizzle ORM schema definitions from the metadata
func (g *DrizzleGenerator) Generate(meta *pgmeta.GeneratorMetadata, opts Options) (string, error) {
	ctx := newDrizzleContext(meta, opts)
	return ctx.generate()
}

// drizzleContext holds the context for Drizzle generation
type drizzleContext struct {
	meta                *pgmeta.GeneratorMetadata
	opts                Options
	columnsByTable       map[string][]pgmeta.PostgresColumn       // key: schema.table
	relationshipsByTable map[string][]pgmeta.PostgresRelationship // key: schema.table
	primaryKeysByTable   map[string][]pgmeta.PrimaryKey           // key: schema.table
	enumsBySchema        map[string][]pgmeta.PostgresType
	tablesBySchema       map[string][]pgmeta.PostgresTable
}

func newDrizzleContext(meta *pgmeta.GeneratorMetadata, opts Options) *drizzleContext {
	ctx := &drizzleContext{
		meta:                 meta,
		opts:                 opts,
		columnsByTable:       make(map[string][]pgmeta.PostgresColumn),
		relationshipsByTable: make(map[string][]pgmeta.PostgresRelationship),
		primaryKeysByTable:   make(map[string][]pgmeta.PrimaryKey),
		enumsBySchema:        make(map[string][]pgmeta.PostgresType),
		tablesBySchema:       make(map[string][]pgmeta.PostgresTable),
	}
	ctx.buildIndexes()
	return ctx
}

func (ctx *drizzleContext) buildIndexes() {
	// Index columns by table
	for _, col := range ctx.meta.Columns {
		key := col.Schema + "." + col.Table
		ctx.columnsByTable[key] = append(ctx.columnsByTable[key], col)
	}

	// Index relationships by table
	for _, rel := range ctx.meta.Relationships {
		key := rel.Schema + "." + rel.Relation
		ctx.relationshipsByTable[key] = append(ctx.relationshipsByTable[key], rel)
	}

	// Index primary keys by table
	for _, t := range ctx.meta.Tables {
		key := t.Schema + "." + t.Name
		ctx.primaryKeysByTable[key] = t.PrimaryKeys
		ctx.tablesBySchema[t.Schema] = append(ctx.tablesBySchema[t.Schema], t)
	}

	// Index enums by schema
	for _, t := range ctx.meta.Types {
		if len(t.Enums) > 0 {
			ctx.enumsBySchema[t.Schema] = append(ctx.enumsBySchema[t.Schema], t)
		}
	}
}

func (ctx *drizzleContext) generate() (string, error) {
	var sb strings.Builder

	// Collect all imports needed
	imports := ctx.collectImports()

	// Write header
	sb.WriteString("// Generated by pg-meta\n")
	sb.WriteString("// Drizzle ORM schema definitions\n\n")

	// Write imports
	sb.WriteString("import {\n")
	for _, imp := range imports {
		sb.WriteString(fmt.Sprintf("  %s,\n", imp))
	}
	sb.WriteString("} from 'drizzle-orm/pg-core';\n")

	// Check if we need relations import
	if len(ctx.meta.Relationships) > 0 {
		sb.WriteString("import { relations } from 'drizzle-orm';\n")
	}
	sb.WriteString("\n")

	// Get sorted schemas
	schemas := ctx.getSortedSchemas()

	for _, schemaName := range schemas {
		// Generate enums first
		if enums, ok := ctx.enumsBySchema[schemaName]; ok {
			for _, enum := range enums {
				ctx.generateEnum(&sb, enum)
			}
		}

		// Generate tables
		if tables, ok := ctx.tablesBySchema[schemaName]; ok {
			// Sort tables by name
			sort.Slice(tables, func(i, j int) bool {
				return tables[i].Name < tables[j].Name
			})

			for _, table := range tables {
				ctx.generateTable(&sb, table)
			}
		}
	}

	// Generate relations after all tables
	for _, schemaName := range schemas {
		if tables, ok := ctx.tablesBySchema[schemaName]; ok {
			for _, table := range tables {
				ctx.generateRelations(&sb, table)
			}
		}
	}

	return sb.String(), nil
}

func (ctx *drizzleContext) collectImports() []string {
	importSet := make(map[string]bool)
	importSet["pgTable"] = true

	for _, col := range ctx.meta.Columns {
		imp := ctx.getDrizzleImportForType(col)
		if imp != "" {
			importSet[imp] = true
		}
	}

	// Check for enums
	if len(ctx.meta.Types) > 0 {
		for _, t := range ctx.meta.Types {
			if len(t.Enums) > 0 {
				importSet["pgEnum"] = true
				break
			}
		}
	}

	// Convert to sorted slice
	imports := make([]string, 0, len(importSet))
	for imp := range importSet {
		imports = append(imports, imp)
	}
	sort.Strings(imports)
	return imports
}

func (ctx *drizzleContext) getDrizzleImportForType(col pgmeta.PostgresColumn) string {
	// Handle arrays
	if col.DataType == "ARRAY" {
		return ctx.getDrizzleImportForFormat(strings.TrimPrefix(col.Format, "_"))
	}
	return ctx.getDrizzleImportForFormat(col.Format)
}

func (ctx *drizzleContext) getDrizzleImportForFormat(format string) string {
	switch format {
	case "int2", "smallint":
		return "smallint"
	case "int4", "integer", "int":
		return "integer"
	case "int8", "bigint":
		return "bigint"
	case "float4", "real":
		return "real"
	case "float8", "double precision":
		return "doublePrecision"
	case "numeric", "decimal":
		return "numeric"
	case "serial", "serial4":
		return "serial"
	case "bigserial", "serial8":
		return "bigserial"
	case "smallserial", "serial2":
		return "smallserial"
	case "text":
		return "text"
	case "varchar", "character varying":
		return "varchar"
	case "char", "character", "bpchar":
		return "char"
	case "bool", "boolean":
		return "boolean"
	case "date":
		return "date"
	case "time", "time without time zone":
		return "time"
	case "timetz", "time with time zone":
		return "time"
	case "timestamp", "timestamp without time zone":
		return "timestamp"
	case "timestamptz", "timestamp with time zone":
		return "timestamp"
	case "interval":
		return "interval"
	case "json":
		return "json"
	case "jsonb":
		return "jsonb"
	case "uuid":
		return "uuid"
	case "bytea":
		return "bytea" // Note: Drizzle uses customType for bytea typically
	case "inet":
		return "inet"
	case "cidr":
		return "cidr"
	case "macaddr":
		return "macaddr"
	default:
		// Check if it's an enum
		for _, t := range ctx.meta.Types {
			if t.Name == format && len(t.Enums) > 0 {
				return "" // Enum reference, no import needed
			}
		}
		return "text" // fallback
	}
}

func (ctx *drizzleContext) generateEnum(sb *strings.Builder, enum pgmeta.PostgresType) {
	varName := toCamelCase(enum.Name) + "Enum"

	sb.WriteString(fmt.Sprintf("// Enum: %s.%s\n", enum.Schema, enum.Name))
	sb.WriteString(fmt.Sprintf("export const %s = pgEnum('%s', [\n", varName, enum.Name))
	for _, val := range enum.Enums {
		sb.WriteString(fmt.Sprintf("  '%s',\n", val))
	}
	sb.WriteString("]);\n\n")
}

func (ctx *drizzleContext) generateTable(sb *strings.Builder, table pgmeta.PostgresTable) {
	key := table.Schema + "." + table.Name
	columns := ctx.columnsByTable[key]
	primaryKeys := ctx.primaryKeysByTable[key]

	// Sort columns by ordinal position
	sort.Slice(columns, func(i, j int) bool {
		return columns[i].OrdinalPosition < columns[j].OrdinalPosition
	})

	varName := toCamelCase(table.Name)

	if table.Comment != nil && *table.Comment != "" {
		sb.WriteString(fmt.Sprintf("// %s\n", *table.Comment))
	}
	sb.WriteString(fmt.Sprintf("export const %s = pgTable('%s', {\n", varName, table.Name))

	for _, col := range columns {
		ctx.generateColumn(sb, col, primaryKeys)
	}

	sb.WriteString("});\n\n")
}

func (ctx *drizzleContext) generateColumn(sb *strings.Builder, col pgmeta.PostgresColumn, primaryKeys []pgmeta.PrimaryKey) {
	colName := toCamelCase(col.Name)
	drizzleType := ctx.getDrizzleColumnType(col)

	// Check if this column is a primary key
	isPrimaryKey := false
	for _, pk := range primaryKeys {
		if pk.Name == col.Name {
			isPrimaryKey = true
			break
		}
	}

	// Start column definition
	sb.WriteString(fmt.Sprintf("  %s: %s", colName, drizzleType))

	// Add modifiers
	if isPrimaryKey {
		sb.WriteString(".primaryKey()")
	}

	if !col.IsNullable && !isPrimaryKey {
		sb.WriteString(".notNull()")
	}

	if col.IsUnique && !isPrimaryKey {
		sb.WriteString(".unique()")
	}

	if col.DefaultValue != nil {
		defaultVal := *col.DefaultValue
		// Handle common default value patterns
		if strings.Contains(defaultVal, "now()") || strings.Contains(defaultVal, "CURRENT_TIMESTAMP") {
			sb.WriteString(".defaultNow()")
		} else if strings.Contains(defaultVal, "gen_random_uuid()") || strings.Contains(defaultVal, "uuid_generate_v4()") {
			sb.WriteString(".defaultRandom()")
		} else if defaultVal == "true" || defaultVal == "false" {
			sb.WriteString(fmt.Sprintf(".default(%s)", defaultVal))
		} else if strings.HasPrefix(defaultVal, "'") && strings.Contains(defaultVal, "::") {
			// Handle casted string literals like 'value'::type
			parts := strings.Split(defaultVal, "::")
			sb.WriteString(fmt.Sprintf(".default(%s)", parts[0]))
		} else if isNumeric(defaultVal) {
			sb.WriteString(fmt.Sprintf(".default(%s)", defaultVal))
		}
		// Skip complex defaults like sequences
	}

	sb.WriteString(",\n")
}

func (ctx *drizzleContext) getDrizzleColumnType(col pgmeta.PostgresColumn) string {
	// Check for serial/identity columns first
	if col.IsIdentity {
		switch col.Format {
		case "int2":
			return "smallserial('id')"
		case "int8", "bigint":
			return fmt.Sprintf("bigserial('%s')", col.Name)
		default:
			return fmt.Sprintf("serial('%s')", col.Name)
		}
	}

	// Check for enum types
	for _, t := range ctx.meta.Types {
		if t.Name == col.Format && len(t.Enums) > 0 {
			enumVarName := toCamelCase(t.Name) + "Enum"
			return fmt.Sprintf("%s('%s')", enumVarName, col.Name)
		}
	}

	// Handle arrays
	if col.DataType == "ARRAY" {
		baseType := strings.TrimPrefix(col.Format, "_")
		baseTypeStr := ctx.getDrizzleTypeString(baseType, col.Name)
		return fmt.Sprintf("%s.array()", baseTypeStr)
	}

	return ctx.getDrizzleTypeString(col.Format, col.Name)
}

func (ctx *drizzleContext) getDrizzleTypeString(format, colName string) string {
	switch format {
	case "int2", "smallint":
		return fmt.Sprintf("smallint('%s')", colName)
	case "int4", "integer", "int":
		return fmt.Sprintf("integer('%s')", colName)
	case "int8", "bigint":
		return fmt.Sprintf("bigint('%s', { mode: 'number' })", colName)
	case "float4", "real":
		return fmt.Sprintf("real('%s')", colName)
	case "float8", "double precision":
		return fmt.Sprintf("doublePrecision('%s')", colName)
	case "numeric", "decimal":
		return fmt.Sprintf("numeric('%s')", colName)
	case "text":
		return fmt.Sprintf("text('%s')", colName)
	case "varchar", "character varying":
		return fmt.Sprintf("varchar('%s')", colName)
	case "char", "character", "bpchar":
		return fmt.Sprintf("char('%s')", colName)
	case "bool", "boolean":
		return fmt.Sprintf("boolean('%s')", colName)
	case "date":
		return fmt.Sprintf("date('%s')", colName)
	case "time", "time without time zone":
		return fmt.Sprintf("time('%s')", colName)
	case "timetz", "time with time zone":
		return fmt.Sprintf("time('%s', { withTimezone: true })", colName)
	case "timestamp", "timestamp without time zone":
		return fmt.Sprintf("timestamp('%s')", colName)
	case "timestamptz", "timestamp with time zone":
		return fmt.Sprintf("timestamp('%s', { withTimezone: true })", colName)
	case "interval":
		return fmt.Sprintf("interval('%s')", colName)
	case "json":
		return fmt.Sprintf("json('%s')", colName)
	case "jsonb":
		return fmt.Sprintf("jsonb('%s')", colName)
	case "uuid":
		return fmt.Sprintf("uuid('%s')", colName)
	case "bytea":
		return fmt.Sprintf("bytea('%s')", colName) // Note: may need customType
	case "inet":
		return fmt.Sprintf("inet('%s')", colName)
	case "cidr":
		return fmt.Sprintf("cidr('%s')", colName)
	case "macaddr":
		return fmt.Sprintf("macaddr('%s')", colName)
	default:
		return fmt.Sprintf("text('%s')", colName) // fallback
	}
}

func (ctx *drizzleContext) generateRelations(sb *strings.Builder, table pgmeta.PostgresTable) {
	key := table.Schema + "." + table.Name
	rels := ctx.relationshipsByTable[key]

	if len(rels) == 0 {
		return
	}

	varName := toCamelCase(table.Name)
	relationsVarName := varName + "Relations"

	sb.WriteString(fmt.Sprintf("export const %s = relations(%s, ({ one }) => ({\n", relationsVarName, varName))

	for _, rel := range rels {
		refTableVar := toCamelCase(rel.ReferencedRelation)
		relName := toCamelCase(rel.ReferencedRelation)

		// Handle case where column names suggest a better relation name
		if len(rel.Columns) == 1 {
			colName := rel.Columns[0]
			if strings.HasSuffix(colName, "_id") {
				relName = toCamelCase(strings.TrimSuffix(colName, "_id"))
			}
		}

		sb.WriteString(fmt.Sprintf("  %s: one(%s, {\n", relName, refTableVar))
		sb.WriteString(fmt.Sprintf("    fields: [%s.%s],\n", varName, toCamelCase(rel.Columns[0])))
		sb.WriteString(fmt.Sprintf("    references: [%s.%s],\n", refTableVar, toCamelCase(rel.ReferencedColumns[0])))
		sb.WriteString("  }),\n")
	}

	sb.WriteString("}));\n\n")
}

func (ctx *drizzleContext) getSortedSchemas() []string {
	schemaSet := make(map[string]bool)
	for _, s := range ctx.meta.Schemas {
		schemaSet[s.Name] = true
	}

	schemas := make([]string, 0, len(schemaSet))
	for s := range schemaSet {
		schemas = append(schemas, s)
	}
	sort.Strings(schemas)
	return schemas
}

// toCamelCase converts snake_case to camelCase
func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// isNumeric checks if a string is a numeric value
func isNumeric(s string) bool {
	if len(s) == 0 {
		return false
	}
	for i, c := range s {
		if c == '-' && i == 0 {
			continue
		}
		if c == '.' {
			continue
		}
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}
