package generators

import (
	"fmt"
	"sort"
	"strings"

	"github.com/supabase/postgres-meta/cli/pkg/pgmeta"
)

// KyselyGenerator generates Kysely type definitions
type KyselyGenerator struct{}

// Name returns the generator name
func (g *KyselyGenerator) Name() string {
	return "kysely"
}

// Generate generates Kysely type definitions from the metadata
func (g *KyselyGenerator) Generate(meta *pgmeta.GeneratorMetadata, opts Options) (string, error) {
	ctx := newKyselyContext(meta)
	return ctx.generate()
}

// kyselyContext holds the context for Kysely generation
type kyselyContext struct {
	meta        *pgmeta.GeneratorMetadata
	types       map[string]pgmeta.PostgresType
	userEnums   map[string][]string
	columns     map[int64][]pgmeta.PostgresColumn
	schemas     map[string]pgmeta.PostgresSchema
	schemaNames map[string]bool
}

func newKyselyContext(meta *pgmeta.GeneratorMetadata) *kyselyContext {
	ctx := &kyselyContext{
		meta:        meta,
		types:       make(map[string]pgmeta.PostgresType),
		userEnums:   make(map[string][]string),
		columns:     make(map[int64][]pgmeta.PostgresColumn),
		schemas:     make(map[string]pgmeta.PostgresSchema),
		schemaNames: make(map[string]bool),
	}

	// Build indexes
	for _, schema := range meta.Schemas {
		ctx.schemas[schema.Name] = schema
		ctx.schemaNames[schema.Name] = true
	}

	for _, t := range meta.Types {
		ctx.types[t.Name] = t
		if len(t.Enums) > 0 {
			ctx.userEnums[t.Schema+"."+t.Name] = t.Enums
		}
	}

	// Sort and group columns by table_id
	sortedColumns := make([]pgmeta.PostgresColumn, len(meta.Columns))
	copy(sortedColumns, meta.Columns)
	sort.Slice(sortedColumns, func(i, j int) bool {
		return sortedColumns[i].OrdinalPosition < sortedColumns[j].OrdinalPosition
	})

	for _, col := range sortedColumns {
		ctx.columns[col.TableID] = append(ctx.columns[col.TableID], col)
	}

	return ctx
}

func (ctx *kyselyContext) generate() (string, error) {
	var sb strings.Builder

	sb.WriteString(`// Generated by pg-meta
// Kysely type definitions

import type { ColumnType, Generated, Insertable, Selectable, Updateable } from 'kysely';

`)

	// Generate enum types
	for _, t := range ctx.meta.Types {
		if len(t.Enums) > 0 && ctx.schemaNames[t.Schema] {
			sb.WriteString(ctx.generateEnum(t))
			sb.WriteString("\n\n")
		}
	}

	// Generate table interfaces
	for _, table := range ctx.meta.Tables {
		if !ctx.schemaNames[table.Schema] {
			continue
		}
		sb.WriteString(ctx.generateTable(table))
		sb.WriteString("\n\n")
	}

	// Generate view interfaces
	for _, view := range ctx.meta.Views {
		if !ctx.schemaNames[view.Schema] {
			continue
		}
		sb.WriteString(ctx.generateView(view))
		sb.WriteString("\n\n")
	}

	// Generate materialized view interfaces
	for _, matview := range ctx.meta.MaterializedViews {
		if !ctx.schemaNames[matview.Schema] {
			continue
		}
		sb.WriteString(ctx.generateMaterializedView(matview))
		sb.WriteString("\n\n")
	}

	// Generate Database interface
	sb.WriteString(ctx.generateDatabaseInterface())

	return sb.String(), nil
}

func (ctx *kyselyContext) generateEnum(t pgmeta.PostgresType) string {
	var sb strings.Builder
	typeName := toKyselyTypeName(t.Name)

	variants := make([]string, len(t.Enums))
	for i, v := range t.Enums {
		variants[i] = fmt.Sprintf("'%s'", v)
	}

	sb.WriteString(fmt.Sprintf("export type %s = %s;", typeName, strings.Join(variants, " | ")))

	return sb.String()
}

func (ctx *kyselyContext) generateTable(table pgmeta.PostgresTable) string {
	var sb strings.Builder
	tableName := toKyselyTypeName(table.Name)
	cols := ctx.columns[table.ID]

	// Table interface with ColumnType for generated columns
	sb.WriteString(fmt.Sprintf("export interface %sTable {\n", tableName))
	for _, col := range cols {
		colType := ctx.columnToKyselyType(col)
		sb.WriteString(fmt.Sprintf("  %s: %s;\n", col.Name, colType))
	}
	sb.WriteString("}\n\n")

	// Type aliases for Selectable, Insertable, Updateable
	sb.WriteString(fmt.Sprintf("export type %s = Selectable<%sTable>;\n", tableName, tableName))
	sb.WriteString(fmt.Sprintf("export type New%s = Insertable<%sTable>;\n", tableName, tableName))
	sb.WriteString(fmt.Sprintf("export type %sUpdate = Updateable<%sTable>;", tableName, tableName))

	return sb.String()
}

func (ctx *kyselyContext) generateView(view pgmeta.PostgresView) string {
	var sb strings.Builder
	viewName := toKyselyTypeName(view.Name)
	cols := ctx.columns[view.ID]

	// View interface (read-only, no ColumnType wrappers)
	sb.WriteString(fmt.Sprintf("export interface %sView {\n", viewName))
	for _, col := range cols {
		colType := ctx.columnToSimpleType(col)
		if col.IsNullable {
			colType += " | null"
		}
		sb.WriteString(fmt.Sprintf("  %s: %s;\n", col.Name, colType))
	}
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("export type %s = Selectable<%sView>;", viewName, viewName))

	return sb.String()
}

func (ctx *kyselyContext) generateMaterializedView(matview pgmeta.PostgresMaterializedView) string {
	var sb strings.Builder
	viewName := toKyselyTypeName(matview.Name)
	cols := ctx.columns[matview.ID]

	// Materialized view interface (read-only)
	sb.WriteString(fmt.Sprintf("export interface %sView {\n", viewName))
	for _, col := range cols {
		colType := ctx.columnToSimpleType(col)
		if col.IsNullable {
			colType += " | null"
		}
		sb.WriteString(fmt.Sprintf("  %s: %s;\n", col.Name, colType))
	}
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("export type %s = Selectable<%sView>;", viewName, viewName))

	return sb.String()
}

func (ctx *kyselyContext) generateDatabaseInterface() string {
	var sb strings.Builder

	sb.WriteString("export interface Database {\n")

	// Add tables
	for _, table := range ctx.meta.Tables {
		if !ctx.schemaNames[table.Schema] {
			continue
		}
		tableName := toKyselyTypeName(table.Name)
		sb.WriteString(fmt.Sprintf("  %s: %sTable;\n", table.Name, tableName))
	}

	// Add views
	for _, view := range ctx.meta.Views {
		if !ctx.schemaNames[view.Schema] {
			continue
		}
		viewName := toKyselyTypeName(view.Name)
		sb.WriteString(fmt.Sprintf("  %s: %sView;\n", view.Name, viewName))
	}

	// Add materialized views
	for _, matview := range ctx.meta.MaterializedViews {
		if !ctx.schemaNames[matview.Schema] {
			continue
		}
		viewName := toKyselyTypeName(matview.Name)
		sb.WriteString(fmt.Sprintf("  %s: %sView;\n", matview.Name, viewName))
	}

	sb.WriteString("}\n")

	return sb.String()
}

func (ctx *kyselyContext) columnToKyselyType(col pgmeta.PostgresColumn) string {
	baseType := ctx.columnToSimpleType(col)

	// Handle nullable
	if col.IsNullable {
		baseType += " | null"
	}

	// Handle generated/identity columns
	if col.IsIdentity || col.IsGenerated {
		return fmt.Sprintf("Generated<%s>", baseType)
	}

	// Handle columns with defaults (optional on insert)
	if col.DefaultValue != nil {
		return fmt.Sprintf("ColumnType<%s, %s | undefined, %s>", baseType, baseType, baseType)
	}

	return baseType
}

func (ctx *kyselyContext) columnToSimpleType(col pgmeta.PostgresColumn) string {
	format := col.Format

	// Check if it's an array type
	if strings.HasPrefix(format, "_") {
		innerType := ctx.pgTypeToTsType(format[1:], col.Schema)
		return innerType + "[]"
	}

	return ctx.pgTypeToTsType(format, col.Schema)
}

func (ctx *kyselyContext) pgTypeToTsType(pgType, schema string) string {
	// Check if it's an enum
	if _, ok := ctx.userEnums[schema+"."+pgType]; ok {
		return toKyselyTypeName(pgType)
	}

	// Map PostgreSQL types to TypeScript types
	switch pgType {
	// Boolean
	case "bool":
		return "boolean"

	// Integer types
	case "int2", "int4":
		return "number"
	case "int8":
		return "string" // bigint as string to preserve precision

	// Floating point
	case "float4", "float8", "numeric":
		return "number"

	// String types
	case "varchar", "bpchar", "text", "citext", "name", "char":
		return "string"

	// Date/Time types
	case "date":
		return "string"
	case "time", "timetz":
		return "string"
	case "timestamp", "timestamptz":
		return "Date"

	// UUID
	case "uuid":
		return "string"

	// JSON types
	case "json", "jsonb":
		return "unknown"

	// Binary
	case "bytea":
		return "Buffer"

	// Network types
	case "inet", "cidr", "macaddr", "macaddr8":
		return "string"

	// Geometric types
	case "point", "line", "lseg", "box", "path", "polygon", "circle":
		return "string"

	// Range types
	case "int4range", "int8range", "numrange", "tsrange", "tstzrange", "daterange":
		return "string"

	// Other types
	case "money":
		return "string"
	case "interval":
		return "string"
	case "xml":
		return "string"
	case "tsvector", "tsquery":
		return "string"
	case "void":
		return "void"
	case "record":
		return "Record<string, unknown>"

	default:
		return "unknown"
	}
}

func toKyselyTypeName(name string) string {
	var result strings.Builder
	capitalizeNext := true

	for _, r := range name {
		if r == '_' || r == '-' || r == ' ' {
			capitalizeNext = true
			continue
		}
		if capitalizeNext {
			if r >= 'a' && r <= 'z' {
				result.WriteRune(r - 32) // uppercase
			} else {
				result.WriteRune(r)
			}
			capitalizeNext = false
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
