// Generated by pg-meta generate types swift
// This is an example output from the Pokemon schema

import Foundation
import Supabase

public enum PublicSchema {
  // =============================================================================
  // ENUMS
  // =============================================================================

  public enum BattleTerrain: String, Codable, Hashable, Sendable {
    case normal = "normal"
    case electric = "electric"
    case grassy = "grassy"
    case misty = "misty"
    case psychic = "psychic"
  }

  public enum EvolutionMethod: String, Codable, Hashable, Sendable {
    case levelUp = "level_up"
    case trade = "trade"
    case item = "item"
    case friendship = "friendship"
    case timeOfDay = "time_of_day"
    case location = "location"
    case special = "special"
  }

  public enum MoveCategory: String, Codable, Hashable, Sendable {
    case physical = "physical"
    case special = "special"
    case status = "status"
  }

  public enum PokemonNature: String, Codable, Hashable, Sendable {
    case hardy = "hardy"
    case lonely = "lonely"
    case brave = "brave"
    case adamant = "adamant"
    case naughty = "naughty"
    case bold = "bold"
    case docile = "docile"
    case relaxed = "relaxed"
    case impish = "impish"
    case lax = "lax"
    case timid = "timid"
    case hasty = "hasty"
    case serious = "serious"
    case jolly = "jolly"
    case naive = "naive"
    case modest = "modest"
    case mild = "mild"
    case quiet = "quiet"
    case bashful = "bashful"
    case rash = "rash"
    case calm = "calm"
    case gentle = "gentle"
    case sassy = "sassy"
    case careful = "careful"
    case quirky = "quirky"
  }

  public enum PokemonType: String, Codable, Hashable, Sendable {
    case normal = "normal"
    case fire = "fire"
    case water = "water"
    case electric = "electric"
    case grass = "grass"
    case ice = "ice"
    case fighting = "fighting"
    case poison = "poison"
    case ground = "ground"
    case flying = "flying"
    case psychic = "psychic"
    case bug = "bug"
    case rock = "rock"
    case ghost = "ghost"
    case dragon = "dragon"
    case dark = "dark"
    case steel = "steel"
    case fairy = "fairy"
  }

  public enum StatusCondition: String, Codable, Hashable, Sendable {
    case none = "none"
    case burned = "burned"
    case frozen = "frozen"
    case paralyzed = "paralyzed"
    case poisoned = "poisoned"
    case badlyPoisoned = "badly_poisoned"
    case asleep = "asleep"
  }

  public enum WeatherCondition: String, Codable, Hashable, Sendable {
    case clear = "clear"
    case sunny = "sunny"
    case rain = "rain"
    case sandstorm = "sandstorm"
    case hail = "hail"
    case snow = "snow"
    case fog = "fog"
  }

  // =============================================================================
  // TABLE STRUCTS
  // =============================================================================

  public struct AbilitiesSelect: Codable, Hashable, Sendable, Identifiable {
    public var id: Int32 { _id }
    public let _id: Int32
    public let name: String
    public let description: String
    public let isHidden: Bool?
    public let generationIntroduced: Int32
    public let createdAt: String?

    public enum CodingKeys: String, CodingKey {
      case _id = "id"
      case name = "name"
      case description = "description"
      case isHidden = "is_hidden"
      case generationIntroduced = "generation_introduced"
      case createdAt = "created_at"
    }
  }

  public struct AbilitiesInsert: Codable, Hashable, Sendable {
    public let id: Int32?
    public let name: String
    public let description: String
    public let isHidden: Bool?
    public let generationIntroduced: Int32?
    public let createdAt: String?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case name = "name"
      case description = "description"
      case isHidden = "is_hidden"
      case generationIntroduced = "generation_introduced"
      case createdAt = "created_at"
    }
  }

  public struct AbilitiesUpdate: Codable, Hashable, Sendable {
    public let id: Int32?
    public let name: String?
    public let description: String?
    public let isHidden: Bool?
    public let generationIntroduced: Int32?
    public let createdAt: String?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case name = "name"
      case description = "description"
      case isHidden = "is_hidden"
      case generationIntroduced = "generation_introduced"
      case createdAt = "created_at"
    }
  }

  public struct BattlesSelect: Codable, Hashable, Sendable, Identifiable {
    public var id: UUID { _id }
    public let _id: UUID
    public let format: String
    public let terrain: BattleTerrain?
    public let weather: WeatherCondition?
    public let trainer1Id: UUID
    public let trainer2Id: UUID
    public let winnerId: UUID?
    public let startedAt: String?
    public let endedAt: String?
    public let turns: Int32?
    public let isRanked: Bool?
    public let replayData: AnyJSON?

    public enum CodingKeys: String, CodingKey {
      case _id = "id"
      case format = "format"
      case terrain = "terrain"
      case weather = "weather"
      case trainer1Id = "trainer1_id"
      case trainer2Id = "trainer2_id"
      case winnerId = "winner_id"
      case startedAt = "started_at"
      case endedAt = "ended_at"
      case turns = "turns"
      case isRanked = "is_ranked"
      case replayData = "replay_data"
    }
  }

  public struct BattlesInsert: Codable, Hashable, Sendable {
    public let id: UUID?
    public let format: String
    public let terrain: BattleTerrain?
    public let weather: WeatherCondition?
    public let trainer1Id: UUID
    public let trainer2Id: UUID
    public let winnerId: UUID?
    public let startedAt: String?
    public let endedAt: String?
    public let turns: Int32?
    public let isRanked: Bool?
    public let replayData: AnyJSON?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case format = "format"
      case terrain = "terrain"
      case weather = "weather"
      case trainer1Id = "trainer1_id"
      case trainer2Id = "trainer2_id"
      case winnerId = "winner_id"
      case startedAt = "started_at"
      case endedAt = "ended_at"
      case turns = "turns"
      case isRanked = "is_ranked"
      case replayData = "replay_data"
    }
  }

  public struct BattlesUpdate: Codable, Hashable, Sendable {
    public let id: UUID?
    public let format: String?
    public let terrain: BattleTerrain?
    public let weather: WeatherCondition?
    public let trainer1Id: UUID?
    public let trainer2Id: UUID?
    public let winnerId: UUID?
    public let startedAt: String?
    public let endedAt: String?
    public let turns: Int32?
    public let isRanked: Bool?
    public let replayData: AnyJSON?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case format = "format"
      case terrain = "terrain"
      case weather = "weather"
      case trainer1Id = "trainer1_id"
      case trainer2Id = "trainer2_id"
      case winnerId = "winner_id"
      case startedAt = "started_at"
      case endedAt = "ended_at"
      case turns = "turns"
      case isRanked = "is_ranked"
      case replayData = "replay_data"
    }
  }

  public struct MovesSelect: Codable, Hashable, Sendable, Identifiable {
    public var id: Int32 { _id }
    public let _id: Int32
    public let name: String
    public let moveType: PokemonType
    public let category: MoveCategory
    public let power: Int32?
    public let accuracy: Int32?
    public let pp: Int32
    public let priority: Int32
    public let target: String
    public let makesContact: Bool?
    public let effectDescription: String?
    public let effectChance: Int32?
    public let statusInflicted: StatusCondition?
    public let statChanges: AnyJSON?
    public let generationIntroduced: Int32
    public let isZMove: Bool?
    public let isMaxMove: Bool?
    public let createdAt: String?

    public enum CodingKeys: String, CodingKey {
      case _id = "id"
      case name = "name"
      case moveType = "move_type"
      case category = "category"
      case power = "power"
      case accuracy = "accuracy"
      case pp = "pp"
      case priority = "priority"
      case target = "target"
      case makesContact = "makes_contact"
      case effectDescription = "effect_description"
      case effectChance = "effect_chance"
      case statusInflicted = "status_inflicted"
      case statChanges = "stat_changes"
      case generationIntroduced = "generation_introduced"
      case isZMove = "is_z_move"
      case isMaxMove = "is_max_move"
      case createdAt = "created_at"
    }
  }

  public struct MovesInsert: Codable, Hashable, Sendable {
    public let id: Int32?
    public let name: String
    public let moveType: PokemonType
    public let category: MoveCategory
    public let power: Int32?
    public let accuracy: Int32?
    public let pp: Int32
    public let priority: Int32?
    public let target: String
    public let makesContact: Bool?
    public let effectDescription: String?
    public let effectChance: Int32?
    public let statusInflicted: StatusCondition?
    public let statChanges: AnyJSON?
    public let generationIntroduced: Int32?
    public let isZMove: Bool?
    public let isMaxMove: Bool?
    public let createdAt: String?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case name = "name"
      case moveType = "move_type"
      case category = "category"
      case power = "power"
      case accuracy = "accuracy"
      case pp = "pp"
      case priority = "priority"
      case target = "target"
      case makesContact = "makes_contact"
      case effectDescription = "effect_description"
      case effectChance = "effect_chance"
      case statusInflicted = "status_inflicted"
      case statChanges = "stat_changes"
      case generationIntroduced = "generation_introduced"
      case isZMove = "is_z_move"
      case isMaxMove = "is_max_move"
      case createdAt = "created_at"
    }
  }

  public struct MovesUpdate: Codable, Hashable, Sendable {
    public let id: Int32?
    public let name: String?
    public let moveType: PokemonType?
    public let category: MoveCategory?
    public let power: Int32?
    public let accuracy: Int32?
    public let pp: Int32?
    public let priority: Int32?
    public let target: String?
    public let makesContact: Bool?
    public let effectDescription: String?
    public let effectChance: Int32?
    public let statusInflicted: StatusCondition?
    public let statChanges: AnyJSON?
    public let generationIntroduced: Int32?
    public let isZMove: Bool?
    public let isMaxMove: Bool?
    public let createdAt: String?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case name = "name"
      case moveType = "move_type"
      case category = "category"
      case power = "power"
      case accuracy = "accuracy"
      case pp = "pp"
      case priority = "priority"
      case target = "target"
      case makesContact = "makes_contact"
      case effectDescription = "effect_description"
      case effectChance = "effect_chance"
      case statusInflicted = "status_inflicted"
      case statChanges = "stat_changes"
      case generationIntroduced = "generation_introduced"
      case isZMove = "is_z_move"
      case isMaxMove = "is_max_move"
      case createdAt = "created_at"
    }
  }

  public struct PokemonSelect: Codable, Hashable, Sendable, Identifiable {
    public var id: UUID { _id }
    public let _id: UUID
    public let speciesId: Int32
    public let trainerId: UUID?
    public let nickname: String?
    public let level: Int32
    public let experience: Int32
    public let nature: PokemonNature
    public let abilityId: Int32
    public let gender: String?
    public let isShiny: Bool?
    public let currentHp: Int32
    public let status: StatusCondition?
    public let happiness: Int32
    public let heldItem: String?
    public let pokeballType: String?
    public let originalTrainerId: UUID?
    public let caughtAt: String?
    public let caughtLocationId: Int32?
    public let caughtLevel: Int32?
    public let isEgg: Bool?
    public let eggCyclesRemaining: Int32?
    public let formId: Int32?
    public let dynamaxLevel: Int32?
    public let canGigantamax: Bool?
    public let teraType: PokemonType?
    public let createdAt: String?
    public let updatedAt: String?

    public enum CodingKeys: String, CodingKey {
      case _id = "id"
      case speciesId = "species_id"
      case trainerId = "trainer_id"
      case nickname = "nickname"
      case level = "level"
      case experience = "experience"
      case nature = "nature"
      case abilityId = "ability_id"
      case gender = "gender"
      case isShiny = "is_shiny"
      case currentHp = "current_hp"
      case status = "status"
      case happiness = "happiness"
      case heldItem = "held_item"
      case pokeballType = "pokeball_type"
      case originalTrainerId = "original_trainer_id"
      case caughtAt = "caught_at"
      case caughtLocationId = "caught_location_id"
      case caughtLevel = "caught_level"
      case isEgg = "is_egg"
      case eggCyclesRemaining = "egg_cycles_remaining"
      case formId = "form_id"
      case dynamaxLevel = "dynamax_level"
      case canGigantamax = "can_gigantamax"
      case teraType = "tera_type"
      case createdAt = "created_at"
      case updatedAt = "updated_at"
    }
  }

  public struct TrainersSelect: Codable, Hashable, Sendable, Identifiable {
    public var id: UUID { _id }
    public let _id: UUID
    public let username: String
    public let email: String
    public let displayName: String?
    public let avatarUrl: String?
    public let homeRegionId: Int32?
    public let trainerClass: String?
    public let badgesEarned: [Int32]?
    public let pokedexSeen: Int32?
    public let pokedexCaught: Int32?
    public let totalBattles: Int32?
    public let battlesWon: Int32?
    public let bio: String?
    public let isVerified: Bool?
    public let isChampion: Bool?
    public let createdAt: String?
    public let updatedAt: String?
    public let lastActiveAt: String?

    public enum CodingKeys: String, CodingKey {
      case _id = "id"
      case username = "username"
      case email = "email"
      case displayName = "display_name"
      case avatarUrl = "avatar_url"
      case homeRegionId = "home_region_id"
      case trainerClass = "trainer_class"
      case badgesEarned = "badges_earned"
      case pokedexSeen = "pokedex_seen"
      case pokedexCaught = "pokedex_caught"
      case totalBattles = "total_battles"
      case battlesWon = "battles_won"
      case bio = "bio"
      case isVerified = "is_verified"
      case isChampion = "is_champion"
      case createdAt = "created_at"
      case updatedAt = "updated_at"
      case lastActiveAt = "last_active_at"
    }
  }

  public struct RegionsSelect: Codable, Hashable, Sendable, Identifiable {
    public var id: Int32 { _id }
    public let _id: Int32
    public let name: String
    public let generation: Int32
    public let description: String?
    public let createdAt: String?
    public let updatedAt: String?

    public enum CodingKeys: String, CodingKey {
      case _id = "id"
      case name = "name"
      case generation = "generation"
      case description = "description"
      case createdAt = "created_at"
      case updatedAt = "updated_at"
    }
  }

  public struct TeamsSelect: Codable, Hashable, Sendable, Identifiable {
    public var id: UUID { _id }
    public let _id: UUID
    public let trainerId: UUID
    public let name: String
    public let description: String?
    public let isActive: Bool?
    public let format: String?
    public let createdAt: String?
    public let updatedAt: String?

    public enum CodingKeys: String, CodingKey {
      case _id = "id"
      case trainerId = "trainer_id"
      case name = "name"
      case description = "description"
      case isActive = "is_active"
      case format = "format"
      case createdAt = "created_at"
      case updatedAt = "updated_at"
    }
  }

  // =============================================================================
  // VIEW STRUCTS
  // =============================================================================

  public struct TrainerStatsSelect: Codable, Hashable, Sendable {
    public let id: UUID?
    public let username: String?
    public let displayName: String?
    public let trainerClass: String?
    public let totalBattles: Int32?
    public let battlesWon: Int32?
    public let winRate: Double?
    public let pokedexCaught: Int32?
    public let totalPokemon: Int64?
    public let shinyCount: Int64?
    public let badgeCount: Int32?
    public let isChampion: Bool?
    public let memberSince: String?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case username = "username"
      case displayName = "display_name"
      case trainerClass = "trainer_class"
      case totalBattles = "total_battles"
      case battlesWon = "battles_won"
      case winRate = "win_rate"
      case pokedexCaught = "pokedex_caught"
      case totalPokemon = "total_pokemon"
      case shinyCount = "shiny_count"
      case badgeCount = "badge_count"
      case isChampion = "is_champion"
      case memberSince = "member_since"
    }
  }

  public struct PokemonFullSelect: Codable, Hashable, Sendable {
    public let id: UUID?
    public let nickname: String?
    public let speciesName: String?
    public let nationalDexNumber: Int32?
    public let primaryType: PokemonType?
    public let secondaryType: PokemonType?
    public let level: Int32?
    public let nature: PokemonNature?
    public let abilityName: String?
    public let gender: String?
    public let isShiny: Bool?
    public let currentHp: Int32?
    public let status: StatusCondition?
    public let happiness: Int32?
    public let heldItem: String?
    public let trainerUsername: String?
    public let caughtLocation: String?
    public let caughtRegion: String?
    public let caughtAt: String?

    public enum CodingKeys: String, CodingKey {
      case id = "id"
      case nickname = "nickname"
      case speciesName = "species_name"
      case nationalDexNumber = "national_dex_number"
      case primaryType = "primary_type"
      case secondaryType = "secondary_type"
      case level = "level"
      case nature = "nature"
      case abilityName = "ability_name"
      case gender = "gender"
      case isShiny = "is_shiny"
      case currentHp = "current_hp"
      case status = "status"
      case happiness = "happiness"
      case heldItem = "held_item"
      case trainerUsername = "trainer_username"
      case caughtLocation = "caught_location"
      case caughtRegion = "caught_region"
      case caughtAt = "caught_at"
    }
  }

  // =============================================================================
  // COMPOSITE TYPES
  // =============================================================================

  public struct PokemonStats: Codable, Hashable, Sendable {
    public let hp: Int32?
    public let attack: Int32?
    public let defense: Int32?
    public let specialAttack: Int32?
    public let specialDefense: Int32?
    public let speed: Int32?

    public enum CodingKeys: String, CodingKey {
      case hp = "hp"
      case attack = "attack"
      case defense = "defense"
      case specialAttack = "special_attack"
      case specialDefense = "special_defense"
      case speed = "speed"
    }
  }

  public struct GeoLocation: Codable, Hashable, Sendable {
    public let latitude: Decimal?
    public let longitude: Decimal?
    public let altitude: Int32?

    public enum CodingKeys: String, CodingKey {
      case latitude = "latitude"
      case longitude = "longitude"
      case altitude = "altitude"
    }
  }
}
