// Generated by pg-meta
// Drizzle ORM schema definitions

import {
  bigint,
  boolean,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// Enum: public.battle_terrain
export const battleTerrainEnum = pgEnum('battle_terrain', [
  'normal',
  'electric',
  'grassy',
  'misty',
  'psychic',
]);

// Enum: public.evolution_method
export const evolutionMethodEnum = pgEnum('evolution_method', [
  'level_up',
  'trade',
  'item',
  'friendship',
  'time_of_day',
  'location',
  'special',
]);

// Enum: public.move_category
export const moveCategoryEnum = pgEnum('move_category', [
  'physical',
  'special',
  'status',
]);

// Enum: public.pokemon_nature
export const pokemonNatureEnum = pgEnum('pokemon_nature', [
  'hardy',
  'lonely',
  'brave',
  'adamant',
  'naughty',
  'bold',
  'docile',
  'relaxed',
  'impish',
  'lax',
  'timid',
  'hasty',
  'serious',
  'jolly',
  'naive',
  'modest',
  'mild',
  'quiet',
  'bashful',
  'rash',
  'calm',
  'gentle',
  'sassy',
  'careful',
  'quirky',
]);

// Enum: public.pokemon_type
export const pokemonTypeEnum = pgEnum('pokemon_type', [
  'normal',
  'fire',
  'water',
  'electric',
  'grass',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'psychic',
  'bug',
  'rock',
  'ghost',
  'dragon',
  'dark',
  'steel',
  'fairy',
]);

// Enum: public.status_condition
export const statusConditionEnum = pgEnum('status_condition', [
  'none',
  'burned',
  'frozen',
  'paralyzed',
  'poisoned',
  'badly_poisoned',
  'asleep',
]);

// Enum: public.weather_condition
export const weatherConditionEnum = pgEnum('weather_condition', [
  'clear',
  'sunny',
  'rain',
  'sandstorm',
  'hail',
  'snow',
  'fog',
]);

export const abilities = pgTable('abilities', {
  id: integer('id').primaryKey(),
  name: varchar('name').notNull().unique(),
  description: text('description').notNull(),
  isHidden: boolean('is_hidden').default(false),
  generationIntroduced: integer('generation_introduced').notNull().default(1),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const battleLogs = pgTable('battle_logs', {
  id: integer('id').primaryKey(),
  battleId: uuid('battle_id').notNull(),
  turn: integer('turn').notNull(),
  actionOrder: integer('action_order').notNull(),
  actorTrainerId: uuid('actor_trainer_id').notNull(),
  actionType: varchar('action_type').notNull(),
  actionDetails: jsonb('action_details').notNull(),
  result: jsonb('result'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

// Battle records between trainers
export const battles = pgTable('battles', {
  id: uuid('id').primaryKey().defaultRandom(),
  format: varchar('format').notNull(),
  terrain: battleTerrainEnum('terrain').default('normal'),
  weather: weatherConditionEnum('weather').default('clear'),
  trainer1Id: uuid('trainer1_id').notNull(),
  trainer2Id: uuid('trainer2_id').notNull(),
  winnerId: uuid('winner_id'),
  startedAt: timestamp('started_at', { withTimezone: true }).defaultNow(),
  endedAt: timestamp('ended_at', { withTimezone: true }),
  turns: integer('turns'),
  isRanked: boolean('is_ranked').default(false),
  replayData: jsonb('replay_data'),
});

export const evolutionChains = pgTable('evolution_chains', {
  id: integer('id').primaryKey(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const evolutions = pgTable('evolutions', {
  id: integer('id').primaryKey(),
  chainId: integer('chain_id').notNull(),
  fromSpeciesId: integer('from_species_id').notNull(),
  toSpeciesId: integer('to_species_id').notNull(),
  method: evolutionMethodEnum('method').notNull(),
  levelRequired: integer('level_required'),
  itemRequired: varchar('item_required'),
  tradeSpeciesId: integer('trade_species_id'),
  timeOfDay: varchar('time_of_day'),
  locationId: integer('location_id'),
  minHappiness: integer('min_happiness'),
  minAffection: integer('min_affection'),
  knownMove: varchar('known_move'),
  gender: varchar('gender'),
  heldItem: varchar('held_item'),
  weather: weatherConditionEnum('weather'),
  otherConditions: jsonb('other_conditions'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const items = pgTable('items', {
  id: integer('id').primaryKey(),
  name: varchar('name').notNull().unique(),
  category: varchar('category').notNull(),
  description: text('description').notNull(),
  buyPrice: integer('buy_price'),
  sellPrice: integer('sell_price'),
  effect: jsonb('effect'),
  isHoldable: boolean('is_holdable').default(false),
  isConsumable: boolean('is_consumable').default(false),
  flingPower: integer('fling_power'),
  flingEffect: text('fling_effect'),
  spriteUrl: text('sprite_url'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const locations = pgTable('locations', {
  id: integer('id').primaryKey(),
  regionId: integer('region_id').notNull(),
  name: varchar('name').notNull(),
  locationType: varchar('location_type').notNull(),
  coordinates: text('coordinates'),
  hasPokemonCenter: boolean('has_pokemon_center').default(false),
  hasPokemart: boolean('has_pokemart').default(false),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const moves = pgTable('moves', {
  id: integer('id').primaryKey(),
  name: varchar('name').notNull().unique(),
  moveType: pokemonTypeEnum('move_type').notNull(),
  category: moveCategoryEnum('category').notNull(),
  power: integer('power'),
  accuracy: integer('accuracy'),
  pp: integer('pp').notNull(),
  priority: integer('priority').notNull().default(0),
  target: varchar('target').notNull(),
  makesContact: boolean('makes_contact').default(false),
  effectDescription: text('effect_description'),
  effectChance: integer('effect_chance'),
  statusInflicted: statusConditionEnum('status_inflicted'),
  statChanges: jsonb('stat_changes'),
  generationIntroduced: integer('generation_introduced').notNull().default(1),
  isZMove: boolean('is_z_move').default(false),
  isMaxMove: boolean('is_max_move').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const pokedexEntries = pgTable('pokedex_entries', {
  id: integer('id').primaryKey(),
  trainerId: uuid('trainer_id').notNull(),
  pokemonSpeciesId: integer('pokemon_species_id').notNull(),
  seen: boolean('seen').default(true),
  caught: boolean('caught').default(false),
  firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).defaultNow(),
  firstCaughtAt: timestamp('first_caught_at', { withTimezone: true }),
  timesCaught: integer('times_caught').default(0),
});

// Individual Pokemon instances owned by trainers
export const pokemon = pgTable('pokemon', {
  id: uuid('id').primaryKey().defaultRandom(),
  speciesId: integer('species_id').notNull(),
  trainerId: uuid('trainer_id'),
  nickname: varchar('nickname'),
  level: integer('level').notNull().default(1),
  experience: integer('experience').notNull().default(0),
  nature: pokemonNatureEnum('nature').notNull(),
  abilityId: integer('ability_id').notNull(),
  gender: varchar('gender'),
  isShiny: boolean('is_shiny').default(false),
  individualValues: text('individual_values').notNull(),
  effortValues: text('effort_values').notNull(),
  currentHp: integer('current_hp').notNull(),
  status: statusConditionEnum('status').default('none'),
  happiness: integer('happiness').notNull().default(70),
  heldItem: varchar('held_item'),
  pokeballType: varchar('pokeball_type').default('poke_ball'),
  originalTrainerId: uuid('original_trainer_id'),
  caughtAt: timestamp('caught_at', { withTimezone: true }).defaultNow(),
  caughtLocationId: integer('caught_location_id'),
  caughtLevel: integer('caught_level'),
  isEgg: boolean('is_egg').default(false),
  eggCyclesRemaining: integer('egg_cycles_remaining'),
  formId: integer('form_id'),
  dynamaxLevel: integer('dynamax_level').default(0),
  canGigantamax: boolean('can_gigantamax').default(false),
  teraType: pokemonTypeEnum('tera_type'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const pokemonKnownMoves = pgTable('pokemon_known_moves', {
  id: integer('id').primaryKey(),
  pokemonId: uuid('pokemon_id').notNull(),
  moveId: integer('move_id').notNull(),
  slot: integer('slot').notNull(),
  ppRemaining: integer('pp_remaining').notNull(),
  ppUps: integer('pp_ups').default(0),
});

export const pokemonMoves = pgTable('pokemon_moves', {
  id: integer('id').primaryKey(),
  pokemonSpeciesId: integer('pokemon_species_id').notNull(),
  moveId: integer('move_id').notNull(),
  learnMethod: varchar('learn_method').notNull(),
  levelLearned: integer('level_learned'),
  tmNumber: varchar('tm_number'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

// The Pokedex entries - master list of all Pokemon species
export const pokemonSpecies = pgTable('pokemon_species', {
  id: integer('id').primaryKey(),
  nationalDexNumber: integer('national_dex_number').notNull().unique(),
  name: varchar('name').notNull().unique(),
  primaryType: pokemonTypeEnum('primary_type').notNull(),
  secondaryType: pokemonTypeEnum('secondary_type'),
  baseStats: text('base_stats').notNull(),
  heightCm: integer('height_cm').notNull(),
  weightGrams: integer('weight_grams').notNull(),
  catchRate: integer('catch_rate').notNull(),
  baseExperience: integer('base_experience').notNull(),
  baseHappiness: integer('base_happiness').notNull().default(70),
  growthRate: varchar('growth_rate').notNull(),
  eggGroups: text('egg_groups').array().notNull().default('{}'),
  genderRatio: numeric('gender_ratio'),
  eggCycles: integer('egg_cycles').notNull().default(20),
  isLegendary: boolean('is_legendary').default(false),
  isMythical: boolean('is_mythical').default(false),
  isBaby: boolean('is_baby').default(false),
  generation: integer('generation').notNull(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const pokemonSpeciesAbilities = pgTable('pokemon_species_abilities', {
  id: integer('id').primaryKey(),
  pokemonSpeciesId: integer('pokemon_species_id').notNull(),
  abilityId: integer('ability_id').notNull(),
  isHidden: boolean('is_hidden').default(false),
  slot: integer('slot').notNull(),
});

export const regions = pgTable('regions', {
  id: integer('id').primaryKey(),
  name: varchar('name').notNull().unique(),
  generation: integer('generation').notNull(),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const teamMembers = pgTable('team_members', {
  id: integer('id').primaryKey(),
  teamId: uuid('team_id').notNull(),
  pokemonId: uuid('pokemon_id').notNull(),
  slot: integer('slot').notNull(),
});

export const teams = pgTable('teams', {
  id: uuid('id').primaryKey().defaultRandom(),
  trainerId: uuid('trainer_id').notNull(),
  name: varchar('name').notNull(),
  description: text('description'),
  isActive: boolean('is_active').default(false),
  format: varchar('format'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const trainerInventory = pgTable('trainer_inventory', {
  id: integer('id').primaryKey(),
  trainerId: uuid('trainer_id').notNull(),
  itemId: integer('item_id').notNull(),
  quantity: integer('quantity').notNull().default(1),
});

// Pokemon trainers (users of the system)
export const trainers = pgTable('trainers', {
  id: uuid('id').primaryKey().defaultRandom(),
  username: varchar('username').notNull().unique(),
  email: varchar('email').notNull().unique(),
  displayName: varchar('display_name'),
  avatarUrl: text('avatar_url'),
  homeRegionId: integer('home_region_id'),
  trainerClass: varchar('trainer_class').default('Pokemon Trainer'),
  badgesEarned: integer('badges_earned').array().default('{}'),
  pokedexSeen: integer('pokedex_seen').default(0),
  pokedexCaught: integer('pokedex_caught').default(0),
  totalBattles: integer('total_battles').default(0),
  battlesWon: integer('battles_won').default(0),
  bio: text('bio'),
  isVerified: boolean('is_verified').default(false),
  isChampion: boolean('is_champion').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  lastActiveAt: timestamp('last_active_at', { withTimezone: true }).defaultNow(),
});

export const battleLogsRelations = relations(battleLogs, ({ one }) => ({
  actorTrainer: one(trainers, {
    fields: [battleLogs.actorTrainerId],
    references: [trainers.id],
  }),
  battle: one(battles, {
    fields: [battleLogs.battleId],
    references: [battles.id],
  }),
}));

export const battlesRelations = relations(battles, ({ one }) => ({
  trainer1: one(trainers, {
    fields: [battles.trainer1Id],
    references: [trainers.id],
  }),
  trainer2: one(trainers, {
    fields: [battles.trainer2Id],
    references: [trainers.id],
  }),
  winner: one(trainers, {
    fields: [battles.winnerId],
    references: [trainers.id],
  }),
}));

export const evolutionsRelations = relations(evolutions, ({ one }) => ({
  chain: one(evolutionChains, {
    fields: [evolutions.chainId],
    references: [evolutionChains.id],
  }),
  fromSpecies: one(pokemonSpecies, {
    fields: [evolutions.fromSpeciesId],
    references: [pokemonSpecies.id],
  }),
  location: one(locations, {
    fields: [evolutions.locationId],
    references: [locations.id],
  }),
  toSpecies: one(pokemonSpecies, {
    fields: [evolutions.toSpeciesId],
    references: [pokemonSpecies.id],
  }),
  tradeSpecies: one(pokemonSpecies, {
    fields: [evolutions.tradeSpeciesId],
    references: [pokemonSpecies.id],
  }),
}));

export const locationsRelations = relations(locations, ({ one }) => ({
  region: one(regions, {
    fields: [locations.regionId],
    references: [regions.id],
  }),
}));

export const pokedexEntriesRelations = relations(pokedexEntries, ({ one }) => ({
  pokemonSpecies: one(pokemonSpecies, {
    fields: [pokedexEntries.pokemonSpeciesId],
    references: [pokemonSpecies.id],
  }),
  trainer: one(trainers, {
    fields: [pokedexEntries.trainerId],
    references: [trainers.id],
  }),
}));

export const pokemonRelations = relations(pokemon, ({ one }) => ({
  ability: one(abilities, {
    fields: [pokemon.abilityId],
    references: [abilities.id],
  }),
  caughtLocation: one(locations, {
    fields: [pokemon.caughtLocationId],
    references: [locations.id],
  }),
  species: one(pokemonSpecies, {
    fields: [pokemon.speciesId],
    references: [pokemonSpecies.id],
  }),
  trainer: one(trainers, {
    fields: [pokemon.trainerId],
    references: [trainers.id],
  }),
}));

export const pokemonKnownMovesRelations = relations(pokemonKnownMoves, ({ one }) => ({
  move: one(moves, {
    fields: [pokemonKnownMoves.moveId],
    references: [moves.id],
  }),
  pokemon: one(pokemon, {
    fields: [pokemonKnownMoves.pokemonId],
    references: [pokemon.id],
  }),
}));

export const pokemonMovesRelations = relations(pokemonMoves, ({ one }) => ({
  move: one(moves, {
    fields: [pokemonMoves.moveId],
    references: [moves.id],
  }),
  pokemonSpecies: one(pokemonSpecies, {
    fields: [pokemonMoves.pokemonSpeciesId],
    references: [pokemonSpecies.id],
  }),
}));

export const pokemonSpeciesAbilitiesRelations = relations(pokemonSpeciesAbilities, ({ one }) => ({
  ability: one(abilities, {
    fields: [pokemonSpeciesAbilities.abilityId],
    references: [abilities.id],
  }),
  pokemonSpecies: one(pokemonSpecies, {
    fields: [pokemonSpeciesAbilities.pokemonSpeciesId],
    references: [pokemonSpecies.id],
  }),
}));

export const teamMembersRelations = relations(teamMembers, ({ one }) => ({
  pokemon: one(pokemon, {
    fields: [teamMembers.pokemonId],
    references: [pokemon.id],
  }),
  team: one(teams, {
    fields: [teamMembers.teamId],
    references: [teams.id],
  }),
}));

export const teamsRelations = relations(teams, ({ one }) => ({
  trainer: one(trainers, {
    fields: [teams.trainerId],
    references: [trainers.id],
  }),
}));

export const trainerInventoryRelations = relations(trainerInventory, ({ one }) => ({
  item: one(items, {
    fields: [trainerInventory.itemId],
    references: [items.id],
  }),
  trainer: one(trainers, {
    fields: [trainerInventory.trainerId],
    references: [trainers.id],
  }),
}));

export const trainersRelations = relations(trainers, ({ one }) => ({
  homeRegion: one(regions, {
    fields: [trainers.homeRegionId],
    references: [regions.id],
  }),
}));

