# Generated by pg-meta
# Django model definitions

from django.db import models


class BattleTerrain(models.TextChoices):
    NORMAL = 'normal', 'normal'
    ELECTRIC = 'electric', 'electric'
    GRASSY = 'grassy', 'grassy'
    MISTY = 'misty', 'misty'
    PSYCHIC = 'psychic', 'psychic'


class EvolutionMethod(models.TextChoices):
    LEVEL_UP = 'level_up', 'level_up'
    TRADE = 'trade', 'trade'
    ITEM = 'item', 'item'
    FRIENDSHIP = 'friendship', 'friendship'
    TIME_OF_DAY = 'time_of_day', 'time_of_day'
    LOCATION = 'location', 'location'
    SPECIAL = 'special', 'special'


class MoveCategory(models.TextChoices):
    PHYSICAL = 'physical', 'physical'
    SPECIAL = 'special', 'special'
    STATUS = 'status', 'status'


class PokemonNature(models.TextChoices):
    HARDY = 'hardy', 'hardy'
    LONELY = 'lonely', 'lonely'
    BRAVE = 'brave', 'brave'
    ADAMANT = 'adamant', 'adamant'
    NAUGHTY = 'naughty', 'naughty'
    BOLD = 'bold', 'bold'
    DOCILE = 'docile', 'docile'
    RELAXED = 'relaxed', 'relaxed'
    IMPISH = 'impish', 'impish'
    LAX = 'lax', 'lax'
    TIMID = 'timid', 'timid'
    HASTY = 'hasty', 'hasty'
    SERIOUS = 'serious', 'serious'
    JOLLY = 'jolly', 'jolly'
    NAIVE = 'naive', 'naive'
    MODEST = 'modest', 'modest'
    MILD = 'mild', 'mild'
    QUIET = 'quiet', 'quiet'
    BASHFUL = 'bashful', 'bashful'
    RASH = 'rash', 'rash'
    CALM = 'calm', 'calm'
    GENTLE = 'gentle', 'gentle'
    SASSY = 'sassy', 'sassy'
    CAREFUL = 'careful', 'careful'
    QUIRKY = 'quirky', 'quirky'


class PokemonType(models.TextChoices):
    NORMAL = 'normal', 'normal'
    FIRE = 'fire', 'fire'
    WATER = 'water', 'water'
    ELECTRIC = 'electric', 'electric'
    GRASS = 'grass', 'grass'
    ICE = 'ice', 'ice'
    FIGHTING = 'fighting', 'fighting'
    POISON = 'poison', 'poison'
    GROUND = 'ground', 'ground'
    FLYING = 'flying', 'flying'
    PSYCHIC = 'psychic', 'psychic'
    BUG = 'bug', 'bug'
    ROCK = 'rock', 'rock'
    GHOST = 'ghost', 'ghost'
    DRAGON = 'dragon', 'dragon'
    DARK = 'dark', 'dark'
    STEEL = 'steel', 'steel'
    FAIRY = 'fairy', 'fairy'


class StatusCondition(models.TextChoices):
    NONE = 'none', 'none'
    BURNED = 'burned', 'burned'
    FROZEN = 'frozen', 'frozen'
    PARALYZED = 'paralyzed', 'paralyzed'
    POISONED = 'poisoned', 'poisoned'
    BADLY_POISONED = 'badly_poisoned', 'badly_poisoned'
    ASLEEP = 'asleep', 'asleep'


class WeatherCondition(models.TextChoices):
    CLEAR = 'clear', 'clear'
    SUNNY = 'sunny', 'sunny'
    RAIN = 'rain', 'rain'
    SANDSTORM = 'sandstorm', 'sandstorm'
    HAIL = 'hail', 'hail'
    SNOW = 'snow', 'snow'
    FOG = 'fog', 'fog'


class Abilities(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    is_hidden = models.BooleanField(null=True, blank=True)
    generation_introduced = models.IntegerField()
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'abilities'


class Pokemon(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    pokedex_number = models.IntegerField()
    type1 = models.CharField(max_length=255, choices=PokemonType.choices)
    type2 = models.CharField(max_length=255, choices=PokemonType.choices, null=True, blank=True)
    height_m = models.DecimalField(max_digits=65, decimal_places=30)
    weight_kg = models.DecimalField(max_digits=65, decimal_places=30)
    base_experience = models.IntegerField()
    base_hp = models.IntegerField()
    base_attack = models.IntegerField()
    base_defense = models.IntegerField()
    base_special_attack = models.IntegerField()
    base_special_defense = models.IntegerField()
    base_speed = models.IntegerField()
    sprite_url = models.TextField(null=True, blank=True)
    is_legendary = models.BooleanField(null=True, blank=True)
    is_mythical = models.BooleanField(null=True, blank=True)
    generation_introduced = models.IntegerField()
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'pokemon'


class Trainers(models.Model):
    id = models.UUIDField(primary_key=True)
    username = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    display_name = models.CharField(max_length=255, null=True, blank=True)
    avatar_url = models.TextField(null=True, blank=True)
    trainer_level = models.IntegerField()
    experience_points = models.IntegerField()
    pokecoin_balance = models.IntegerField()
    stardust_balance = models.IntegerField()
    created_at = models.DateTimeField(null=True, blank=True)
    last_login_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'trainers'


class Moves(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255, choices=PokemonType.choices)
    category = models.CharField(max_length=255, choices=MoveCategory.choices)
    power = models.IntegerField(null=True, blank=True)
    accuracy = models.IntegerField(null=True, blank=True)
    pp = models.IntegerField()
    priority = models.IntegerField()
    description = models.TextField()
    effect_chance = models.IntegerField(null=True, blank=True)
    target = models.CharField(max_length=255)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'moves'


class TrainerPokemon(models.Model):
    id = models.UUIDField(primary_key=True)
    trainer = models.ForeignKey('Trainers', on_delete=models.CASCADE, db_column='trainer_id')
    pokemon = models.ForeignKey('Pokemon', on_delete=models.CASCADE, db_column='pokemon_id')
    nickname = models.CharField(max_length=255, null=True, blank=True)
    level = models.IntegerField()
    experience = models.IntegerField()
    nature = models.CharField(max_length=255, choices=PokemonNature.choices)
    is_shiny = models.BooleanField(null=True, blank=True)
    iv_hp = models.IntegerField()
    iv_attack = models.IntegerField()
    iv_defense = models.IntegerField()
    iv_special_attack = models.IntegerField()
    iv_special_defense = models.IntegerField()
    iv_speed = models.IntegerField()
    ev_hp = models.IntegerField()
    ev_attack = models.IntegerField()
    ev_defense = models.IntegerField()
    ev_special_attack = models.IntegerField()
    ev_special_defense = models.IntegerField()
    ev_speed = models.IntegerField()
    current_hp = models.IntegerField()
    status_condition = models.CharField(max_length=255, choices=StatusCondition.choices, null=True, blank=True)
    friendship = models.IntegerField()
    captured_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'trainer_pokemon'


class Battles(models.Model):
    id = models.UUIDField(primary_key=True)
    trainer1 = models.ForeignKey('Trainers', on_delete=models.CASCADE, db_column='trainer1_id', related_name='battles_as_trainer1')
    trainer2 = models.ForeignKey('Trainers', on_delete=models.CASCADE, db_column='trainer2_id', related_name='battles_as_trainer2')
    winner = models.ForeignKey('Trainers', on_delete=models.CASCADE, db_column='winner_id', null=True, blank=True, related_name='battles_won')
    format = models.CharField(max_length=255)
    started_at = models.DateTimeField(null=True, blank=True)
    ended_at = models.DateTimeField(null=True, blank=True)
    turns = models.IntegerField(null=True, blank=True)
    weather = models.CharField(max_length=255, choices=WeatherCondition.choices, null=True, blank=True)
    terrain = models.CharField(max_length=255, choices=BattleTerrain.choices, null=True, blank=True)
    is_ranked = models.BooleanField(null=True, blank=True)
    replay_data = models.JSONField(null=True, blank=True)

    class Meta:
        db_table = 'battles'


class BattleLogs(models.Model):
    id = models.AutoField(primary_key=True)
    battle = models.ForeignKey('Battles', on_delete=models.CASCADE, db_column='battle_id')
    turn = models.IntegerField()
    actor_trainer = models.ForeignKey('Trainers', on_delete=models.CASCADE, db_column='actor_trainer_id')
    action_type = models.CharField(max_length=255)
    action_order = models.IntegerField()
    action_details = models.JSONField()
    result = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'battle_logs'
