# Generated by pg-meta generate types python
# This is an example output from the Pokemon schema

from __future__ import annotations

import datetime
import uuid
from typing import (
    Annotated,
    Any,
    List,
    Literal,
    NotRequired,
    Optional,
    TypeAlias,
    TypedDict,
)

from pydantic import BaseModel, Field, Json

# =============================================================================
# ENUMS
# =============================================================================

PublicBattleTerrain: TypeAlias = Literal["normal", "electric", "grassy", "misty", "psychic"]

PublicEvolutionMethod: TypeAlias = Literal["level_up", "trade", "item", "friendship", "time_of_day", "location", "special"]

PublicMoveCategory: TypeAlias = Literal["physical", "special", "status"]

PublicPokemonNature: TypeAlias = Literal["hardy", "lonely", "brave", "adamant", "naughty", "bold", "docile", "relaxed", "impish", "lax", "timid", "hasty", "serious", "jolly", "naive", "modest", "mild", "quiet", "bashful", "rash", "calm", "gentle", "sassy", "careful", "quirky"]

PublicPokemonType: TypeAlias = Literal["normal", "fire", "water", "electric", "grass", "ice", "fighting", "poison", "ground", "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy"]

PublicStatusCondition: TypeAlias = Literal["none", "burned", "frozen", "paralyzed", "poisoned", "badly_poisoned", "asleep"]

PublicWeatherCondition: TypeAlias = Literal["clear", "sunny", "rain", "sandstorm", "hail", "snow", "fog"]

# =============================================================================
# TABLE MODELS
# =============================================================================

class PublicAbilities(BaseModel):
    id: int = Field(alias="id")
    name: str = Field(alias="name")
    description: str = Field(alias="description")
    is_hidden: Optional[bool] = Field(alias="is_hidden")
    generation_introduced: int = Field(alias="generation_introduced")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")

class PublicAbilitiesInsert(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    name: Annotated[str, Field(alias="name")]
    description: Annotated[str, Field(alias="description")]
    is_hidden: NotRequired[Annotated[bool, Field(alias="is_hidden")]]
    generation_introduced: NotRequired[Annotated[int, Field(alias="generation_introduced")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]

class PublicAbilitiesUpdate(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    name: NotRequired[Annotated[str, Field(alias="name")]]
    description: NotRequired[Annotated[str, Field(alias="description")]]
    is_hidden: NotRequired[Annotated[bool, Field(alias="is_hidden")]]
    generation_introduced: NotRequired[Annotated[int, Field(alias="generation_introduced")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]

class PublicBattleLogs(BaseModel):
    id: int = Field(alias="id")
    battle_id: uuid.UUID = Field(alias="battle_id")
    turn: int = Field(alias="turn")
    action_order: int = Field(alias="action_order")
    actor_trainer_id: uuid.UUID = Field(alias="actor_trainer_id")
    action_type: str = Field(alias="action_type")
    action_details: Json[Any] = Field(alias="action_details")
    result: Optional[Json[Any]] = Field(alias="result")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")

class PublicBattleLogsInsert(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    battle_id: Annotated[uuid.UUID, Field(alias="battle_id")]
    turn: Annotated[int, Field(alias="turn")]
    action_order: Annotated[int, Field(alias="action_order")]
    actor_trainer_id: Annotated[uuid.UUID, Field(alias="actor_trainer_id")]
    action_type: Annotated[str, Field(alias="action_type")]
    action_details: Annotated[Json[Any], Field(alias="action_details")]
    result: NotRequired[Annotated[Json[Any], Field(alias="result")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]

class PublicBattleLogsUpdate(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    battle_id: NotRequired[Annotated[uuid.UUID, Field(alias="battle_id")]]
    turn: NotRequired[Annotated[int, Field(alias="turn")]]
    action_order: NotRequired[Annotated[int, Field(alias="action_order")]]
    actor_trainer_id: NotRequired[Annotated[uuid.UUID, Field(alias="actor_trainer_id")]]
    action_type: NotRequired[Annotated[str, Field(alias="action_type")]]
    action_details: NotRequired[Annotated[Json[Any], Field(alias="action_details")]]
    result: NotRequired[Annotated[Json[Any], Field(alias="result")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]

class PublicBattles(BaseModel):
    id: uuid.UUID = Field(alias="id")
    format: str = Field(alias="format")
    terrain: Optional[PublicBattleTerrain] = Field(alias="terrain")
    weather: Optional[PublicWeatherCondition] = Field(alias="weather")
    trainer1_id: uuid.UUID = Field(alias="trainer1_id")
    trainer2_id: uuid.UUID = Field(alias="trainer2_id")
    winner_id: Optional[uuid.UUID] = Field(alias="winner_id")
    started_at: Optional[datetime.datetime] = Field(alias="started_at")
    ended_at: Optional[datetime.datetime] = Field(alias="ended_at")
    turns: Optional[int] = Field(alias="turns")
    is_ranked: Optional[bool] = Field(alias="is_ranked")
    replay_data: Optional[Json[Any]] = Field(alias="replay_data")

class PublicBattlesInsert(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    format: Annotated[str, Field(alias="format")]
    terrain: NotRequired[Annotated[PublicBattleTerrain, Field(alias="terrain")]]
    weather: NotRequired[Annotated[PublicWeatherCondition, Field(alias="weather")]]
    trainer1_id: Annotated[uuid.UUID, Field(alias="trainer1_id")]
    trainer2_id: Annotated[uuid.UUID, Field(alias="trainer2_id")]
    winner_id: NotRequired[Annotated[uuid.UUID, Field(alias="winner_id")]]
    started_at: NotRequired[Annotated[datetime.datetime, Field(alias="started_at")]]
    ended_at: NotRequired[Annotated[datetime.datetime, Field(alias="ended_at")]]
    turns: NotRequired[Annotated[int, Field(alias="turns")]]
    is_ranked: NotRequired[Annotated[bool, Field(alias="is_ranked")]]
    replay_data: NotRequired[Annotated[Json[Any], Field(alias="replay_data")]]

class PublicBattlesUpdate(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    format: NotRequired[Annotated[str, Field(alias="format")]]
    terrain: NotRequired[Annotated[PublicBattleTerrain, Field(alias="terrain")]]
    weather: NotRequired[Annotated[PublicWeatherCondition, Field(alias="weather")]]
    trainer1_id: NotRequired[Annotated[uuid.UUID, Field(alias="trainer1_id")]]
    trainer2_id: NotRequired[Annotated[uuid.UUID, Field(alias="trainer2_id")]]
    winner_id: NotRequired[Annotated[uuid.UUID, Field(alias="winner_id")]]
    started_at: NotRequired[Annotated[datetime.datetime, Field(alias="started_at")]]
    ended_at: NotRequired[Annotated[datetime.datetime, Field(alias="ended_at")]]
    turns: NotRequired[Annotated[int, Field(alias="turns")]]
    is_ranked: NotRequired[Annotated[bool, Field(alias="is_ranked")]]
    replay_data: NotRequired[Annotated[Json[Any], Field(alias="replay_data")]]

class PublicMoves(BaseModel):
    id: int = Field(alias="id")
    name: str = Field(alias="name")
    move_type: PublicPokemonType = Field(alias="move_type")
    category: PublicMoveCategory = Field(alias="category")
    power: Optional[int] = Field(alias="power")
    accuracy: Optional[int] = Field(alias="accuracy")
    pp: int = Field(alias="pp")
    priority: int = Field(alias="priority")
    target: str = Field(alias="target")
    makes_contact: Optional[bool] = Field(alias="makes_contact")
    effect_description: Optional[str] = Field(alias="effect_description")
    effect_chance: Optional[int] = Field(alias="effect_chance")
    status_inflicted: Optional[PublicStatusCondition] = Field(alias="status_inflicted")
    stat_changes: Optional[Json[Any]] = Field(alias="stat_changes")
    generation_introduced: int = Field(alias="generation_introduced")
    is_z_move: Optional[bool] = Field(alias="is_z_move")
    is_max_move: Optional[bool] = Field(alias="is_max_move")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")

class PublicMovesInsert(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    name: Annotated[str, Field(alias="name")]
    move_type: Annotated[PublicPokemonType, Field(alias="move_type")]
    category: Annotated[PublicMoveCategory, Field(alias="category")]
    power: NotRequired[Annotated[int, Field(alias="power")]]
    accuracy: NotRequired[Annotated[int, Field(alias="accuracy")]]
    pp: Annotated[int, Field(alias="pp")]
    priority: NotRequired[Annotated[int, Field(alias="priority")]]
    target: Annotated[str, Field(alias="target")]
    makes_contact: NotRequired[Annotated[bool, Field(alias="makes_contact")]]
    effect_description: NotRequired[Annotated[str, Field(alias="effect_description")]]
    effect_chance: NotRequired[Annotated[int, Field(alias="effect_chance")]]
    status_inflicted: NotRequired[Annotated[PublicStatusCondition, Field(alias="status_inflicted")]]
    stat_changes: NotRequired[Annotated[Json[Any], Field(alias="stat_changes")]]
    generation_introduced: NotRequired[Annotated[int, Field(alias="generation_introduced")]]
    is_z_move: NotRequired[Annotated[bool, Field(alias="is_z_move")]]
    is_max_move: NotRequired[Annotated[bool, Field(alias="is_max_move")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]

class PublicMovesUpdate(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    name: NotRequired[Annotated[str, Field(alias="name")]]
    move_type: NotRequired[Annotated[PublicPokemonType, Field(alias="move_type")]]
    category: NotRequired[Annotated[PublicMoveCategory, Field(alias="category")]]
    power: NotRequired[Annotated[int, Field(alias="power")]]
    accuracy: NotRequired[Annotated[int, Field(alias="accuracy")]]
    pp: NotRequired[Annotated[int, Field(alias="pp")]]
    priority: NotRequired[Annotated[int, Field(alias="priority")]]
    target: NotRequired[Annotated[str, Field(alias="target")]]
    makes_contact: NotRequired[Annotated[bool, Field(alias="makes_contact")]]
    effect_description: NotRequired[Annotated[str, Field(alias="effect_description")]]
    effect_chance: NotRequired[Annotated[int, Field(alias="effect_chance")]]
    status_inflicted: NotRequired[Annotated[PublicStatusCondition, Field(alias="status_inflicted")]]
    stat_changes: NotRequired[Annotated[Json[Any], Field(alias="stat_changes")]]
    generation_introduced: NotRequired[Annotated[int, Field(alias="generation_introduced")]]
    is_z_move: NotRequired[Annotated[bool, Field(alias="is_z_move")]]
    is_max_move: NotRequired[Annotated[bool, Field(alias="is_max_move")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]

class PublicPokemon(BaseModel):
    id: uuid.UUID = Field(alias="id")
    species_id: int = Field(alias="species_id")
    trainer_id: Optional[uuid.UUID] = Field(alias="trainer_id")
    nickname: Optional[str] = Field(alias="nickname")
    level: int = Field(alias="level")
    experience: int = Field(alias="experience")
    nature: PublicPokemonNature = Field(alias="nature")
    ability_id: int = Field(alias="ability_id")
    gender: Optional[str] = Field(alias="gender")
    is_shiny: Optional[bool] = Field(alias="is_shiny")
    current_hp: int = Field(alias="current_hp")
    status: Optional[PublicStatusCondition] = Field(alias="status")
    happiness: int = Field(alias="happiness")
    held_item: Optional[str] = Field(alias="held_item")
    pokeball_type: Optional[str] = Field(alias="pokeball_type")
    original_trainer_id: Optional[uuid.UUID] = Field(alias="original_trainer_id")
    caught_at: Optional[datetime.datetime] = Field(alias="caught_at")
    caught_location_id: Optional[int] = Field(alias="caught_location_id")
    caught_level: Optional[int] = Field(alias="caught_level")
    is_egg: Optional[bool] = Field(alias="is_egg")
    egg_cycles_remaining: Optional[int] = Field(alias="egg_cycles_remaining")
    form_id: Optional[int] = Field(alias="form_id")
    dynamax_level: Optional[int] = Field(alias="dynamax_level")
    can_gigantamax: Optional[bool] = Field(alias="can_gigantamax")
    tera_type: Optional[PublicPokemonType] = Field(alias="tera_type")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")
    updated_at: Optional[datetime.datetime] = Field(alias="updated_at")

class PublicPokemonInsert(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    species_id: Annotated[int, Field(alias="species_id")]
    trainer_id: NotRequired[Annotated[uuid.UUID, Field(alias="trainer_id")]]
    nickname: NotRequired[Annotated[str, Field(alias="nickname")]]
    level: NotRequired[Annotated[int, Field(alias="level")]]
    experience: NotRequired[Annotated[int, Field(alias="experience")]]
    nature: Annotated[PublicPokemonNature, Field(alias="nature")]
    ability_id: Annotated[int, Field(alias="ability_id")]
    gender: NotRequired[Annotated[str, Field(alias="gender")]]
    is_shiny: NotRequired[Annotated[bool, Field(alias="is_shiny")]]
    current_hp: Annotated[int, Field(alias="current_hp")]
    status: NotRequired[Annotated[PublicStatusCondition, Field(alias="status")]]
    happiness: NotRequired[Annotated[int, Field(alias="happiness")]]
    held_item: NotRequired[Annotated[str, Field(alias="held_item")]]
    pokeball_type: NotRequired[Annotated[str, Field(alias="pokeball_type")]]
    original_trainer_id: NotRequired[Annotated[uuid.UUID, Field(alias="original_trainer_id")]]
    caught_at: NotRequired[Annotated[datetime.datetime, Field(alias="caught_at")]]
    caught_location_id: NotRequired[Annotated[int, Field(alias="caught_location_id")]]
    caught_level: NotRequired[Annotated[int, Field(alias="caught_level")]]
    is_egg: NotRequired[Annotated[bool, Field(alias="is_egg")]]
    egg_cycles_remaining: NotRequired[Annotated[int, Field(alias="egg_cycles_remaining")]]
    form_id: NotRequired[Annotated[int, Field(alias="form_id")]]
    dynamax_level: NotRequired[Annotated[int, Field(alias="dynamax_level")]]
    can_gigantamax: NotRequired[Annotated[bool, Field(alias="can_gigantamax")]]
    tera_type: NotRequired[Annotated[PublicPokemonType, Field(alias="tera_type")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicPokemonUpdate(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    species_id: NotRequired[Annotated[int, Field(alias="species_id")]]
    trainer_id: NotRequired[Annotated[uuid.UUID, Field(alias="trainer_id")]]
    nickname: NotRequired[Annotated[str, Field(alias="nickname")]]
    level: NotRequired[Annotated[int, Field(alias="level")]]
    experience: NotRequired[Annotated[int, Field(alias="experience")]]
    nature: NotRequired[Annotated[PublicPokemonNature, Field(alias="nature")]]
    ability_id: NotRequired[Annotated[int, Field(alias="ability_id")]]
    gender: NotRequired[Annotated[str, Field(alias="gender")]]
    is_shiny: NotRequired[Annotated[bool, Field(alias="is_shiny")]]
    current_hp: NotRequired[Annotated[int, Field(alias="current_hp")]]
    status: NotRequired[Annotated[PublicStatusCondition, Field(alias="status")]]
    happiness: NotRequired[Annotated[int, Field(alias="happiness")]]
    held_item: NotRequired[Annotated[str, Field(alias="held_item")]]
    pokeball_type: NotRequired[Annotated[str, Field(alias="pokeball_type")]]
    original_trainer_id: NotRequired[Annotated[uuid.UUID, Field(alias="original_trainer_id")]]
    caught_at: NotRequired[Annotated[datetime.datetime, Field(alias="caught_at")]]
    caught_location_id: NotRequired[Annotated[int, Field(alias="caught_location_id")]]
    caught_level: NotRequired[Annotated[int, Field(alias="caught_level")]]
    is_egg: NotRequired[Annotated[bool, Field(alias="is_egg")]]
    egg_cycles_remaining: NotRequired[Annotated[int, Field(alias="egg_cycles_remaining")]]
    form_id: NotRequired[Annotated[int, Field(alias="form_id")]]
    dynamax_level: NotRequired[Annotated[int, Field(alias="dynamax_level")]]
    can_gigantamax: NotRequired[Annotated[bool, Field(alias="can_gigantamax")]]
    tera_type: NotRequired[Annotated[PublicPokemonType, Field(alias="tera_type")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicPokemonSpecies(BaseModel):
    id: int = Field(alias="id")
    national_dex_number: int = Field(alias="national_dex_number")
    name: str = Field(alias="name")
    primary_type: PublicPokemonType = Field(alias="primary_type")
    secondary_type: Optional[PublicPokemonType] = Field(alias="secondary_type")
    height_cm: int = Field(alias="height_cm")
    weight_grams: int = Field(alias="weight_grams")
    catch_rate: int = Field(alias="catch_rate")
    base_experience: int = Field(alias="base_experience")
    base_happiness: int = Field(alias="base_happiness")
    growth_rate: str = Field(alias="growth_rate")
    egg_groups: List[str] = Field(alias="egg_groups")
    gender_ratio: Optional[float] = Field(alias="gender_ratio")
    egg_cycles: int = Field(alias="egg_cycles")
    is_legendary: Optional[bool] = Field(alias="is_legendary")
    is_mythical: Optional[bool] = Field(alias="is_mythical")
    is_baby: Optional[bool] = Field(alias="is_baby")
    generation: int = Field(alias="generation")
    description: Optional[str] = Field(alias="description")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")
    updated_at: Optional[datetime.datetime] = Field(alias="updated_at")

class PublicPokemonSpeciesInsert(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    national_dex_number: Annotated[int, Field(alias="national_dex_number")]
    name: Annotated[str, Field(alias="name")]
    primary_type: Annotated[PublicPokemonType, Field(alias="primary_type")]
    secondary_type: NotRequired[Annotated[PublicPokemonType, Field(alias="secondary_type")]]
    height_cm: Annotated[int, Field(alias="height_cm")]
    weight_grams: Annotated[int, Field(alias="weight_grams")]
    catch_rate: Annotated[int, Field(alias="catch_rate")]
    base_experience: Annotated[int, Field(alias="base_experience")]
    base_happiness: NotRequired[Annotated[int, Field(alias="base_happiness")]]
    growth_rate: Annotated[str, Field(alias="growth_rate")]
    egg_groups: NotRequired[Annotated[List[str], Field(alias="egg_groups")]]
    gender_ratio: NotRequired[Annotated[float, Field(alias="gender_ratio")]]
    egg_cycles: NotRequired[Annotated[int, Field(alias="egg_cycles")]]
    is_legendary: NotRequired[Annotated[bool, Field(alias="is_legendary")]]
    is_mythical: NotRequired[Annotated[bool, Field(alias="is_mythical")]]
    is_baby: NotRequired[Annotated[bool, Field(alias="is_baby")]]
    generation: Annotated[int, Field(alias="generation")]
    description: NotRequired[Annotated[str, Field(alias="description")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicPokemonSpeciesUpdate(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    national_dex_number: NotRequired[Annotated[int, Field(alias="national_dex_number")]]
    name: NotRequired[Annotated[str, Field(alias="name")]]
    primary_type: NotRequired[Annotated[PublicPokemonType, Field(alias="primary_type")]]
    secondary_type: NotRequired[Annotated[PublicPokemonType, Field(alias="secondary_type")]]
    height_cm: NotRequired[Annotated[int, Field(alias="height_cm")]]
    weight_grams: NotRequired[Annotated[int, Field(alias="weight_grams")]]
    catch_rate: NotRequired[Annotated[int, Field(alias="catch_rate")]]
    base_experience: NotRequired[Annotated[int, Field(alias="base_experience")]]
    base_happiness: NotRequired[Annotated[int, Field(alias="base_happiness")]]
    growth_rate: NotRequired[Annotated[str, Field(alias="growth_rate")]]
    egg_groups: NotRequired[Annotated[List[str], Field(alias="egg_groups")]]
    gender_ratio: NotRequired[Annotated[float, Field(alias="gender_ratio")]]
    egg_cycles: NotRequired[Annotated[int, Field(alias="egg_cycles")]]
    is_legendary: NotRequired[Annotated[bool, Field(alias="is_legendary")]]
    is_mythical: NotRequired[Annotated[bool, Field(alias="is_mythical")]]
    is_baby: NotRequired[Annotated[bool, Field(alias="is_baby")]]
    generation: NotRequired[Annotated[int, Field(alias="generation")]]
    description: NotRequired[Annotated[str, Field(alias="description")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicRegions(BaseModel):
    id: int = Field(alias="id")
    name: str = Field(alias="name")
    generation: int = Field(alias="generation")
    description: Optional[str] = Field(alias="description")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")
    updated_at: Optional[datetime.datetime] = Field(alias="updated_at")

class PublicRegionsInsert(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    name: Annotated[str, Field(alias="name")]
    generation: Annotated[int, Field(alias="generation")]
    description: NotRequired[Annotated[str, Field(alias="description")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicRegionsUpdate(TypedDict):
    id: NotRequired[Annotated[int, Field(alias="id")]]
    name: NotRequired[Annotated[str, Field(alias="name")]]
    generation: NotRequired[Annotated[int, Field(alias="generation")]]
    description: NotRequired[Annotated[str, Field(alias="description")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicTrainers(BaseModel):
    id: uuid.UUID = Field(alias="id")
    username: str = Field(alias="username")
    email: str = Field(alias="email")
    display_name: Optional[str] = Field(alias="display_name")
    avatar_url: Optional[str] = Field(alias="avatar_url")
    home_region_id: Optional[int] = Field(alias="home_region_id")
    trainer_class: Optional[str] = Field(alias="trainer_class")
    badges_earned: Optional[List[int]] = Field(alias="badges_earned")
    pokedex_seen: Optional[int] = Field(alias="pokedex_seen")
    pokedex_caught: Optional[int] = Field(alias="pokedex_caught")
    total_battles: Optional[int] = Field(alias="total_battles")
    battles_won: Optional[int] = Field(alias="battles_won")
    bio: Optional[str] = Field(alias="bio")
    is_verified: Optional[bool] = Field(alias="is_verified")
    is_champion: Optional[bool] = Field(alias="is_champion")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")
    updated_at: Optional[datetime.datetime] = Field(alias="updated_at")
    last_active_at: Optional[datetime.datetime] = Field(alias="last_active_at")

class PublicTrainersInsert(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    username: Annotated[str, Field(alias="username")]
    email: Annotated[str, Field(alias="email")]
    display_name: NotRequired[Annotated[str, Field(alias="display_name")]]
    avatar_url: NotRequired[Annotated[str, Field(alias="avatar_url")]]
    home_region_id: NotRequired[Annotated[int, Field(alias="home_region_id")]]
    trainer_class: NotRequired[Annotated[str, Field(alias="trainer_class")]]
    badges_earned: NotRequired[Annotated[List[int], Field(alias="badges_earned")]]
    pokedex_seen: NotRequired[Annotated[int, Field(alias="pokedex_seen")]]
    pokedex_caught: NotRequired[Annotated[int, Field(alias="pokedex_caught")]]
    total_battles: NotRequired[Annotated[int, Field(alias="total_battles")]]
    battles_won: NotRequired[Annotated[int, Field(alias="battles_won")]]
    bio: NotRequired[Annotated[str, Field(alias="bio")]]
    is_verified: NotRequired[Annotated[bool, Field(alias="is_verified")]]
    is_champion: NotRequired[Annotated[bool, Field(alias="is_champion")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]
    last_active_at: NotRequired[Annotated[datetime.datetime, Field(alias="last_active_at")]]

class PublicTrainersUpdate(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    username: NotRequired[Annotated[str, Field(alias="username")]]
    email: NotRequired[Annotated[str, Field(alias="email")]]
    display_name: NotRequired[Annotated[str, Field(alias="display_name")]]
    avatar_url: NotRequired[Annotated[str, Field(alias="avatar_url")]]
    home_region_id: NotRequired[Annotated[int, Field(alias="home_region_id")]]
    trainer_class: NotRequired[Annotated[str, Field(alias="trainer_class")]]
    badges_earned: NotRequired[Annotated[List[int], Field(alias="badges_earned")]]
    pokedex_seen: NotRequired[Annotated[int, Field(alias="pokedex_seen")]]
    pokedex_caught: NotRequired[Annotated[int, Field(alias="pokedex_caught")]]
    total_battles: NotRequired[Annotated[int, Field(alias="total_battles")]]
    battles_won: NotRequired[Annotated[int, Field(alias="battles_won")]]
    bio: NotRequired[Annotated[str, Field(alias="bio")]]
    is_verified: NotRequired[Annotated[bool, Field(alias="is_verified")]]
    is_champion: NotRequired[Annotated[bool, Field(alias="is_champion")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]
    last_active_at: NotRequired[Annotated[datetime.datetime, Field(alias="last_active_at")]]

class PublicTeams(BaseModel):
    id: uuid.UUID = Field(alias="id")
    trainer_id: uuid.UUID = Field(alias="trainer_id")
    name: str = Field(alias="name")
    description: Optional[str] = Field(alias="description")
    is_active: Optional[bool] = Field(alias="is_active")
    format: Optional[str] = Field(alias="format")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")
    updated_at: Optional[datetime.datetime] = Field(alias="updated_at")

class PublicTeamsInsert(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    trainer_id: Annotated[uuid.UUID, Field(alias="trainer_id")]
    name: Annotated[str, Field(alias="name")]
    description: NotRequired[Annotated[str, Field(alias="description")]]
    is_active: NotRequired[Annotated[bool, Field(alias="is_active")]]
    format: NotRequired[Annotated[str, Field(alias="format")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicTeamsUpdate(TypedDict):
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    trainer_id: NotRequired[Annotated[uuid.UUID, Field(alias="trainer_id")]]
    name: NotRequired[Annotated[str, Field(alias="name")]]
    description: NotRequired[Annotated[str, Field(alias="description")]]
    is_active: NotRequired[Annotated[bool, Field(alias="is_active")]]
    format: NotRequired[Annotated[str, Field(alias="format")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

# =============================================================================
# VIEW MODELS (SELECT ONLY)
# =============================================================================

class PublicTrainerStats(BaseModel):
    id: Optional[uuid.UUID] = Field(alias="id")
    username: Optional[str] = Field(alias="username")
    display_name: Optional[str] = Field(alias="display_name")
    trainer_class: Optional[str] = Field(alias="trainer_class")
    total_battles: Optional[int] = Field(alias="total_battles")
    battles_won: Optional[int] = Field(alias="battles_won")
    win_rate: Optional[float] = Field(alias="win_rate")
    pokedex_caught: Optional[int] = Field(alias="pokedex_caught")
    total_pokemon: Optional[int] = Field(alias="total_pokemon")
    shiny_count: Optional[int] = Field(alias="shiny_count")
    badge_count: Optional[int] = Field(alias="badge_count")
    is_champion: Optional[bool] = Field(alias="is_champion")
    member_since: Optional[datetime.datetime] = Field(alias="member_since")

class PublicPokemonFull(BaseModel):
    id: Optional[uuid.UUID] = Field(alias="id")
    nickname: Optional[str] = Field(alias="nickname")
    species_name: Optional[str] = Field(alias="species_name")
    national_dex_number: Optional[int] = Field(alias="national_dex_number")
    primary_type: Optional[PublicPokemonType] = Field(alias="primary_type")
    secondary_type: Optional[PublicPokemonType] = Field(alias="secondary_type")
    level: Optional[int] = Field(alias="level")
    nature: Optional[PublicPokemonNature] = Field(alias="nature")
    ability_name: Optional[str] = Field(alias="ability_name")
    gender: Optional[str] = Field(alias="gender")
    is_shiny: Optional[bool] = Field(alias="is_shiny")
    current_hp: Optional[int] = Field(alias="current_hp")
    status: Optional[PublicStatusCondition] = Field(alias="status")
    happiness: Optional[int] = Field(alias="happiness")
    held_item: Optional[str] = Field(alias="held_item")
    trainer_username: Optional[str] = Field(alias="trainer_username")
    caught_location: Optional[str] = Field(alias="caught_location")
    caught_region: Optional[str] = Field(alias="caught_region")
    caught_at: Optional[datetime.datetime] = Field(alias="caught_at")

class PublicTypeMatchups(BaseModel):
    id: Optional[int] = Field(alias="id")
    name: Optional[str] = Field(alias="name")
    primary_type: Optional[PublicPokemonType] = Field(alias="primary_type")
    secondary_type: Optional[PublicPokemonType] = Field(alias="secondary_type")
    base_stat_total: Optional[int] = Field(alias="base_stat_total")
    is_legendary: Optional[bool] = Field(alias="is_legendary")
    is_mythical: Optional[bool] = Field(alias="is_mythical")

# =============================================================================
# COMPOSITE TYPES
# =============================================================================

class PublicPokemonStats(BaseModel):
    hp: Optional[int] = Field(alias="hp")
    attack: Optional[int] = Field(alias="attack")
    defense: Optional[int] = Field(alias="defense")
    special_attack: Optional[int] = Field(alias="special_attack")
    special_defense: Optional[int] = Field(alias="special_defense")
    speed: Optional[int] = Field(alias="speed")

class PublicGeoLocation(BaseModel):
    latitude: Optional[float] = Field(alias="latitude")
    longitude: Optional[float] = Field(alias="longitude")
    altitude: Optional[int] = Field(alias="altitude")
