// Generated by pg-meta
// Kysely type definitions

import type { ColumnType, Generated, Insertable, Selectable, Updateable } from 'kysely';

export type BattleTerrain = 'normal' | 'electric' | 'grassy' | 'misty' | 'psychic';

export type EvolutionMethod = 'level_up' | 'trade' | 'item' | 'friendship' | 'time_of_day' | 'location' | 'special';

export type MoveCategory = 'physical' | 'special' | 'status';

export type PokemonNature = 'hardy' | 'lonely' | 'brave' | 'adamant' | 'naughty' | 'bold' | 'docile' | 'relaxed' | 'impish' | 'lax' | 'timid' | 'hasty' | 'serious' | 'jolly' | 'naive' | 'modest' | 'mild' | 'quiet' | 'bashful' | 'rash' | 'calm' | 'gentle' | 'sassy' | 'careful' | 'quirky';

export type PokemonType = 'normal' | 'fire' | 'water' | 'electric' | 'grass' | 'ice' | 'fighting' | 'poison' | 'ground' | 'flying' | 'psychic' | 'bug' | 'rock' | 'ghost' | 'dragon' | 'dark' | 'steel' | 'fairy';

export type StatusCondition = 'none' | 'burned' | 'frozen' | 'paralyzed' | 'poisoned' | 'badly_poisoned' | 'asleep';

export type WeatherCondition = 'clear' | 'sunny' | 'rain' | 'sandstorm' | 'hail' | 'snow' | 'fog';

export interface AbilitiesTable {
  id: Generated<number>;
  name: string;
  description: string;
  is_hidden: boolean | null;
  generation_introduced: ColumnType<number, number | undefined, number>;
  created_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
}

export type Abilities = Selectable<AbilitiesTable>;
export type NewAbilities = Insertable<AbilitiesTable>;
export type AbilitiesUpdate = Updateable<AbilitiesTable>;

export interface PokemonTable {
  id: Generated<number>;
  name: string;
  pokedex_number: number;
  type1: PokemonType;
  type2: PokemonType | null;
  height_m: number;
  weight_kg: number;
  base_experience: number;
  base_hp: number;
  base_attack: number;
  base_defense: number;
  base_special_attack: number;
  base_special_defense: number;
  base_speed: number;
  sprite_url: string | null;
  is_legendary: ColumnType<boolean | null, boolean | null | undefined, boolean | null>;
  is_mythical: ColumnType<boolean | null, boolean | null | undefined, boolean | null>;
  generation_introduced: ColumnType<number, number | undefined, number>;
  created_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
}

export type Pokemon = Selectable<PokemonTable>;
export type NewPokemon = Insertable<PokemonTable>;
export type PokemonUpdate = Updateable<PokemonTable>;

export interface TrainersTable {
  id: ColumnType<string, string | undefined, string>;
  username: string;
  email: string;
  display_name: string | null;
  avatar_url: string | null;
  trainer_level: ColumnType<number, number | undefined, number>;
  experience_points: ColumnType<number, number | undefined, number>;
  pokecoin_balance: ColumnType<number, number | undefined, number>;
  stardust_balance: ColumnType<number, number | undefined, number>;
  created_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
  last_login_at: Date | null;
}

export type Trainers = Selectable<TrainersTable>;
export type NewTrainers = Insertable<TrainersTable>;
export type TrainersUpdate = Updateable<TrainersTable>;

export interface MovesTable {
  id: Generated<number>;
  name: string;
  type: PokemonType;
  category: MoveCategory;
  power: number | null;
  accuracy: number | null;
  pp: number;
  priority: ColumnType<number, number | undefined, number>;
  description: string;
  effect_chance: number | null;
  target: string;
  created_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
}

export type Moves = Selectable<MovesTable>;
export type NewMoves = Insertable<MovesTable>;
export type MovesUpdate = Updateable<MovesTable>;

export interface TrainerPokemonTable {
  id: ColumnType<string, string | undefined, string>;
  trainer_id: string;
  pokemon_id: number;
  nickname: string | null;
  level: ColumnType<number, number | undefined, number>;
  experience: ColumnType<number, number | undefined, number>;
  nature: PokemonNature;
  is_shiny: ColumnType<boolean | null, boolean | null | undefined, boolean | null>;
  iv_hp: number;
  iv_attack: number;
  iv_defense: number;
  iv_special_attack: number;
  iv_special_defense: number;
  iv_speed: number;
  ev_hp: ColumnType<number, number | undefined, number>;
  ev_attack: ColumnType<number, number | undefined, number>;
  ev_defense: ColumnType<number, number | undefined, number>;
  ev_special_attack: ColumnType<number, number | undefined, number>;
  ev_special_defense: ColumnType<number, number | undefined, number>;
  ev_speed: ColumnType<number, number | undefined, number>;
  current_hp: number;
  status_condition: ColumnType<StatusCondition | null, StatusCondition | null | undefined, StatusCondition | null>;
  friendship: ColumnType<number, number | undefined, number>;
  captured_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
}

export type TrainerPokemon = Selectable<TrainerPokemonTable>;
export type NewTrainerPokemon = Insertable<TrainerPokemonTable>;
export type TrainerPokemonUpdate = Updateable<TrainerPokemonTable>;

export interface BattlesTable {
  id: ColumnType<string, string | undefined, string>;
  trainer1_id: string;
  trainer2_id: string;
  winner_id: string | null;
  format: string;
  started_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
  ended_at: Date | null;
  turns: number | null;
  weather: WeatherCondition | null;
  terrain: BattleTerrain | null;
  is_ranked: ColumnType<boolean | null, boolean | null | undefined, boolean | null>;
  replay_data: unknown | null;
}

export type Battles = Selectable<BattlesTable>;
export type NewBattles = Insertable<BattlesTable>;
export type BattlesUpdate = Updateable<BattlesTable>;

export interface BattleLogsTable {
  id: Generated<number>;
  battle_id: string;
  turn: number;
  actor_trainer_id: string;
  action_type: string;
  action_order: number;
  action_details: unknown;
  result: unknown | null;
  created_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
}

export type BattleLogs = Selectable<BattleLogsTable>;
export type NewBattleLogs = Insertable<BattleLogsTable>;
export type BattleLogsUpdate = Updateable<BattleLogsTable>;

export interface Database {
  abilities: AbilitiesTable;
  pokemon: PokemonTable;
  trainers: TrainersTable;
  moves: MovesTable;
  trainer_pokemon: TrainerPokemonTable;
  battles: BattlesTable;
  battle_logs: BattleLogsTable;
}
