// Generated by pg-meta generate types typescript
// This is an example output from the Pokemon schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      abilities: {
        Row: {
          created_at: string | null
          description: string
          generation_introduced: number
          id: number
          is_hidden: boolean | null
          name: string
        }
        Insert: {
          created_at?: string | null
          description: string
          generation_introduced?: number
          id?: number
          is_hidden?: boolean | null
          name: string
        }
        Update: {
          created_at?: string | null
          description?: string
          generation_introduced?: number
          id?: number
          is_hidden?: boolean | null
          name?: string
        }
        Relationships: []
      }
      battle_logs: {
        Row: {
          action_details: Json
          action_order: number
          action_type: string
          actor_trainer_id: string
          battle_id: string
          created_at: string | null
          id: number
          result: Json | null
          turn: number
        }
        Insert: {
          action_details: Json
          action_order: number
          action_type: string
          actor_trainer_id: string
          battle_id: string
          created_at?: string | null
          id?: number
          result?: Json | null
          turn: number
        }
        Update: {
          action_details?: Json
          action_order?: number
          action_type?: string
          actor_trainer_id?: string
          battle_id?: string
          created_at?: string | null
          id?: number
          result?: Json | null
          turn?: number
        }
        Relationships: [
          {
            foreignKeyName: "battle_logs_actor_trainer_id_fkey"
            columns: ["actor_trainer_id"]
            isOneToOne: false
            referencedRelation: "trainers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "battle_logs_battle_id_fkey"
            columns: ["battle_id"]
            isOneToOne: false
            referencedRelation: "battles"
            referencedColumns: ["id"]
          }
        ]
      }
      battles: {
        Row: {
          ended_at: string | null
          format: string
          id: string
          is_ranked: boolean | null
          replay_data: Json | null
          started_at: string | null
          terrain: Database["public"]["Enums"]["battle_terrain"] | null
          trainer1_id: string
          trainer2_id: string
          turns: number | null
          weather: Database["public"]["Enums"]["weather_condition"] | null
          winner_id: string | null
        }
        Insert: {
          ended_at?: string | null
          format: string
          id?: string
          is_ranked?: boolean | null
          replay_data?: Json | null
          started_at?: string | null
          terrain?: Database["public"]["Enums"]["battle_terrain"] | null
          trainer1_id: string
          trainer2_id: string
          turns?: number | null
          weather?: Database["public"]["Enums"]["weather_condition"] | null
          winner_id?: string | null
        }
        Update: {
          ended_at?: string | null
          format?: string
          id?: string
          is_ranked?: boolean | null
          replay_data?: Json | null
          started_at?: string | null
          terrain?: Database["public"]["Enums"]["battle_terrain"] | null
          trainer1_id?: string
          trainer2_id?: string
          turns?: number | null
          weather?: Database["public"]["Enums"]["weather_condition"] | null
          winner_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "battles_trainer1_id_fkey"
            columns: ["trainer1_id"]
            isOneToOne: false
            referencedRelation: "trainers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "battles_trainer2_id_fkey"
            columns: ["trainer2_id"]
            isOneToOne: false
            referencedRelation: "trainers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "battles_winner_id_fkey"
            columns: ["winner_id"]
            isOneToOne: false
            referencedRelation: "trainers"
            referencedColumns: ["id"]
          }
        ]
      }
      evolution_chains: {
        Row: {
          created_at: string | null
          id: number
        }
        Insert: {
          created_at?: string | null
          id?: number
        }
        Update: {
          created_at?: string | null
          id?: number
        }
        Relationships: []
      }
      evolutions: {
        Row: {
          chain_id: number
          created_at: string | null
          from_species_id: number
          gender: string | null
          held_item: string | null
          id: number
          item_required: string | null
          known_move: string | null
          level_required: number | null
          location_id: number | null
          method: Database["public"]["Enums"]["evolution_method"]
          min_affection: number | null
          min_happiness: number | null
          other_conditions: Json | null
          time_of_day: string | null
          to_species_id: number
          trade_species_id: number | null
          weather: Database["public"]["Enums"]["weather_condition"] | null
        }
        Insert: {
          chain_id: number
          created_at?: string | null
          from_species_id: number
          gender?: string | null
          held_item?: string | null
          id?: number
          item_required?: string | null
          known_move?: string | null
          level_required?: number | null
          location_id?: number | null
          method: Database["public"]["Enums"]["evolution_method"]
          min_affection?: number | null
          min_happiness?: number | null
          other_conditions?: Json | null
          time_of_day?: string | null
          to_species_id: number
          trade_species_id?: number | null
          weather?: Database["public"]["Enums"]["weather_condition"] | null
        }
        Update: {
          chain_id?: number
          created_at?: string | null
          from_species_id?: number
          gender?: string | null
          held_item?: string | null
          id?: number
          item_required?: string | null
          known_move?: string | null
          level_required?: number | null
          location_id?: number | null
          method?: Database["public"]["Enums"]["evolution_method"]
          min_affection?: number | null
          min_happiness?: number | null
          other_conditions?: Json | null
          time_of_day?: string | null
          to_species_id?: number
          trade_species_id?: number | null
          weather?: Database["public"]["Enums"]["weather_condition"] | null
        }
        Relationships: [
          {
            foreignKeyName: "evolutions_chain_id_fkey"
            columns: ["chain_id"]
            isOneToOne: false
            referencedRelation: "evolution_chains"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evolutions_from_species_id_fkey"
            columns: ["from_species_id"]
            isOneToOne: false
            referencedRelation: "pokemon_species"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evolutions_to_species_id_fkey"
            columns: ["to_species_id"]
            isOneToOne: false
            referencedRelation: "pokemon_species"
            referencedColumns: ["id"]
          }
        ]
      }
      items: {
        Row: {
          buy_price: number | null
          category: string
          created_at: string | null
          description: string
          effect: Json | null
          fling_effect: string | null
          fling_power: number | null
          id: number
          is_consumable: boolean | null
          is_holdable: boolean | null
          name: string
          sell_price: number | null
          sprite_url: string | null
        }
        Insert: {
          buy_price?: number | null
          category: string
          created_at?: string | null
          description: string
          effect?: Json | null
          fling_effect?: string | null
          fling_power?: number | null
          id?: number
          is_consumable?: boolean | null
          is_holdable?: boolean | null
          name: string
          sell_price?: number | null
          sprite_url?: string | null
        }
        Update: {
          buy_price?: number | null
          category?: string
          created_at?: string | null
          description?: string
          effect?: Json | null
          fling_effect?: string | null
          fling_power?: number | null
          id?: number
          is_consumable?: boolean | null
          is_holdable?: boolean | null
          name?: string
          sell_price?: number | null
          sprite_url?: string | null
        }
        Relationships: []
      }
      locations: {
        Row: {
          coordinates: Database["public"]["CompositeTypes"]["geo_location"] | null
          created_at: string | null
          description: string | null
          has_pokemon_center: boolean | null
          has_pokemart: boolean | null
          id: number
          location_type: string
          name: string
          region_id: number
        }
        Insert: {
          coordinates?: Database["public"]["CompositeTypes"]["geo_location"] | null
          created_at?: string | null
          description?: string | null
          has_pokemon_center?: boolean | null
          has_pokemart?: boolean | null
          id?: number
          location_type: string
          name: string
          region_id: number
        }
        Update: {
          coordinates?: Database["public"]["CompositeTypes"]["geo_location"] | null
          created_at?: string | null
          description?: string | null
          has_pokemon_center?: boolean | null
          has_pokemart?: boolean | null
          id?: number
          location_type?: string
          name?: string
          region_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "locations_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          }
        ]
      }
      moves: {
        Row: {
          accuracy: number | null
          category: Database["public"]["Enums"]["move_category"]
          created_at: string | null
          effect_chance: number | null
          effect_description: string | null
          generation_introduced: number
          id: number
          is_max_move: boolean | null
          is_z_move: boolean | null
          makes_contact: boolean | null
          move_type: Database["public"]["Enums"]["pokemon_type"]
          name: string
          power: number | null
          pp: number
          priority: number
          stat_changes: Json | null
          status_inflicted: Database["public"]["Enums"]["status_condition"] | null
          target: string
        }
        Insert: {
          accuracy?: number | null
          category: Database["public"]["Enums"]["move_category"]
          created_at?: string | null
          effect_chance?: number | null
          effect_description?: string | null
          generation_introduced?: number
          id?: number
          is_max_move?: boolean | null
          is_z_move?: boolean | null
          makes_contact?: boolean | null
          move_type: Database["public"]["Enums"]["pokemon_type"]
          name: string
          power?: number | null
          pp: number
          priority?: number
          stat_changes?: Json | null
          status_inflicted?: Database["public"]["Enums"]["status_condition"] | null
          target: string
        }
        Update: {
          accuracy?: number | null
          category?: Database["public"]["Enums"]["move_category"]
          created_at?: string | null
          effect_chance?: number | null
          effect_description?: string | null
          generation_introduced?: number
          id?: number
          is_max_move?: boolean | null
          is_z_move?: boolean | null
          makes_contact?: boolean | null
          move_type?: Database["public"]["Enums"]["pokemon_type"]
          name?: string
          power?: number | null
          pp?: number
          priority?: number
          stat_changes?: Json | null
          status_inflicted?: Database["public"]["Enums"]["status_condition"] | null
          target?: string
        }
        Relationships: []
      }
      pokemon: {
        Row: {
          ability_id: number
          can_gigantamax: boolean | null
          caught_at: string | null
          caught_level: number | null
          caught_location_id: number | null
          created_at: string | null
          current_hp: number
          dynamax_level: number | null
          effort_values: Database["public"]["CompositeTypes"]["pokemon_stats"]
          egg_cycles_remaining: number | null
          experience: number
          form_id: number | null
          gender: string | null
          happiness: number
          held_item: string | null
          id: string
          individual_values: Database["public"]["CompositeTypes"]["pokemon_stats"]
          is_egg: boolean | null
          is_shiny: boolean | null
          level: number
          nature: Database["public"]["Enums"]["pokemon_nature"]
          nickname: string | null
          original_trainer_id: string | null
          pokeball_type: string | null
          species_id: number
          status: Database["public"]["Enums"]["status_condition"] | null
          tera_type: Database["public"]["Enums"]["pokemon_type"] | null
          trainer_id: string | null
          updated_at: string | null
        }
        Insert: {
          ability_id: number
          can_gigantamax?: boolean | null
          caught_at?: string | null
          caught_level?: number | null
          caught_location_id?: number | null
          created_at?: string | null
          current_hp: number
          dynamax_level?: number | null
          effort_values?: Database["public"]["CompositeTypes"]["pokemon_stats"]
          egg_cycles_remaining?: number | null
          experience?: number
          form_id?: number | null
          gender?: string | null
          happiness?: number
          held_item?: string | null
          id?: string
          individual_values: Database["public"]["CompositeTypes"]["pokemon_stats"]
          is_egg?: boolean | null
          is_shiny?: boolean | null
          level?: number
          nature: Database["public"]["Enums"]["pokemon_nature"]
          nickname?: string | null
          original_trainer_id?: string | null
          pokeball_type?: string | null
          species_id: number
          status?: Database["public"]["Enums"]["status_condition"] | null
          tera_type?: Database["public"]["Enums"]["pokemon_type"] | null
          trainer_id?: string | null
          updated_at?: string | null
        }
        Update: {
          ability_id?: number
          can_gigantamax?: boolean | null
          caught_at?: string | null
          caught_level?: number | null
          caught_location_id?: number | null
          created_at?: string | null
          current_hp?: number
          dynamax_level?: number | null
          effort_values?: Database["public"]["CompositeTypes"]["pokemon_stats"]
          egg_cycles_remaining?: number | null
          experience?: number
          form_id?: number | null
          gender?: string | null
          happiness?: number
          held_item?: string | null
          id?: string
          individual_values?: Database["public"]["CompositeTypes"]["pokemon_stats"]
          is_egg?: boolean | null
          is_shiny?: boolean | null
          level?: number
          nature?: Database["public"]["Enums"]["pokemon_nature"]
          nickname?: string | null
          original_trainer_id?: string | null
          pokeball_type?: string | null
          species_id?: number
          status?: Database["public"]["Enums"]["status_condition"] | null
          tera_type?: Database["public"]["Enums"]["pokemon_type"] | null
          trainer_id?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pokemon_ability_id_fkey"
            columns: ["ability_id"]
            isOneToOne: false
            referencedRelation: "abilities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pokemon_species_id_fkey"
            columns: ["species_id"]
            isOneToOne: false
            referencedRelation: "pokemon_species"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pokemon_trainer_id_fkey"
            columns: ["trainer_id"]
            isOneToOne: false
            referencedRelation: "trainers"
            referencedColumns: ["id"]
          }
        ]
      }
      pokemon_species: {
        Row: {
          base_experience: number
          base_happiness: number
          base_stats: Database["public"]["CompositeTypes"]["pokemon_stats"]
          catch_rate: number
          created_at: string | null
          description: string | null
          egg_cycles: number
          egg_groups: string[]
          gender_ratio: number | null
          generation: number
          growth_rate: string
          height_cm: number
          id: number
          is_baby: boolean | null
          is_legendary: boolean | null
          is_mythical: boolean | null
          name: string
          national_dex_number: number
          primary_type: Database["public"]["Enums"]["pokemon_type"]
          secondary_type: Database["public"]["Enums"]["pokemon_type"] | null
          updated_at: string | null
          weight_grams: number
        }
        Insert: {
          base_experience: number
          base_happiness?: number
          base_stats: Database["public"]["CompositeTypes"]["pokemon_stats"]
          catch_rate: number
          created_at?: string | null
          description?: string | null
          egg_cycles?: number
          egg_groups?: string[]
          gender_ratio?: number | null
          generation: number
          growth_rate: string
          height_cm: number
          id?: number
          is_baby?: boolean | null
          is_legendary?: boolean | null
          is_mythical?: boolean | null
          name: string
          national_dex_number: number
          primary_type: Database["public"]["Enums"]["pokemon_type"]
          secondary_type?: Database["public"]["Enums"]["pokemon_type"] | null
          updated_at?: string | null
          weight_grams: number
        }
        Update: {
          base_experience?: number
          base_happiness?: number
          base_stats?: Database["public"]["CompositeTypes"]["pokemon_stats"]
          catch_rate?: number
          created_at?: string | null
          description?: string | null
          egg_cycles?: number
          egg_groups?: string[]
          gender_ratio?: number | null
          generation?: number
          growth_rate?: string
          height_cm?: number
          id?: number
          is_baby?: boolean | null
          is_legendary?: boolean | null
          is_mythical?: boolean | null
          name?: string
          national_dex_number?: number
          primary_type?: Database["public"]["Enums"]["pokemon_type"]
          secondary_type?: Database["public"]["Enums"]["pokemon_type"] | null
          updated_at?: string | null
          weight_grams?: number
        }
        Relationships: []
      }
      regions: {
        Row: {
          created_at: string | null
          description: string | null
          generation: number
          id: number
          name: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          generation: number
          id?: number
          name: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          generation?: number
          id?: number
          name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      teams: {
        Row: {
          created_at: string | null
          description: string | null
          format: string | null
          id: string
          is_active: boolean | null
          name: string
          trainer_id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          format?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          trainer_id: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          format?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          trainer_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "teams_trainer_id_fkey"
            columns: ["trainer_id"]
            isOneToOne: false
            referencedRelation: "trainers"
            referencedColumns: ["id"]
          }
        ]
      }
      trainers: {
        Row: {
          avatar_url: string | null
          badges_earned: number[] | null
          battles_won: number | null
          bio: string | null
          created_at: string | null
          display_name: string | null
          email: string
          home_region_id: number | null
          id: string
          is_champion: boolean | null
          is_verified: boolean | null
          last_active_at: string | null
          pokedex_caught: number | null
          pokedex_seen: number | null
          total_battles: number | null
          trainer_class: string | null
          updated_at: string | null
          username: string
        }
        Insert: {
          avatar_url?: string | null
          badges_earned?: number[] | null
          battles_won?: number | null
          bio?: string | null
          created_at?: string | null
          display_name?: string | null
          email: string
          home_region_id?: number | null
          id?: string
          is_champion?: boolean | null
          is_verified?: boolean | null
          last_active_at?: string | null
          pokedex_caught?: number | null
          pokedex_seen?: number | null
          total_battles?: number | null
          trainer_class?: string | null
          updated_at?: string | null
          username: string
        }
        Update: {
          avatar_url?: string | null
          badges_earned?: number[] | null
          battles_won?: number | null
          bio?: string | null
          created_at?: string | null
          display_name?: string | null
          email?: string
          home_region_id?: number | null
          id?: string
          is_champion?: boolean | null
          is_verified?: boolean | null
          last_active_at?: string | null
          pokedex_caught?: number | null
          pokedex_seen?: number | null
          total_battles?: number | null
          trainer_class?: string | null
          updated_at?: string | null
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "trainers_home_region_id_fkey"
            columns: ["home_region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      pokemon_full: {
        Row: {
          ability_name: string | null
          caught_at: string | null
          caught_location: string | null
          caught_region: string | null
          current_hp: number | null
          effort_values: Database["public"]["CompositeTypes"]["pokemon_stats"] | null
          gender: string | null
          happiness: number | null
          held_item: string | null
          id: string | null
          individual_values: Database["public"]["CompositeTypes"]["pokemon_stats"] | null
          is_shiny: boolean | null
          level: number | null
          national_dex_number: number | null
          nature: Database["public"]["Enums"]["pokemon_nature"] | null
          nickname: string | null
          primary_type: Database["public"]["Enums"]["pokemon_type"] | null
          secondary_type: Database["public"]["Enums"]["pokemon_type"] | null
          species_name: string | null
          status: Database["public"]["Enums"]["status_condition"] | null
          trainer_username: string | null
        }
        Relationships: []
      }
      trainer_stats: {
        Row: {
          badge_count: number | null
          battles_won: number | null
          display_name: string | null
          id: string | null
          is_champion: boolean | null
          member_since: string | null
          pokedex_caught: number | null
          shiny_count: number | null
          total_battles: number | null
          total_pokemon: number | null
          trainer_class: string | null
          username: string | null
          win_rate: number | null
        }
        Relationships: []
      }
      type_matchups: {
        Row: {
          base_stat_total: number | null
          base_stats: Database["public"]["CompositeTypes"]["pokemon_stats"] | null
          id: number | null
          is_legendary: boolean | null
          is_mythical: boolean | null
          name: string | null
          primary_type: Database["public"]["Enums"]["pokemon_type"] | null
          secondary_type: Database["public"]["Enums"]["pokemon_type"] | null
        }
        Relationships: []
      }
    }
    Functions: {
      calculate_stat: {
        Args: {
          base_stat: number
          iv: number
          ev: number
          level: number
          nature_modifier?: number
          is_hp?: boolean
        }
        Returns: number
      }
      get_evolution_chain: {
        Args: {
          species_id: number
        }
        Returns: {
          stage: number
          pokemon_name: string
          evolves_from: string
          method: Database["public"]["Enums"]["evolution_method"]
          requirements: Json
        }[]
      }
      get_pokemon_calculated_stats: {
        Args: {
          pokemon_uuid: string
        }
        Returns: Database["public"]["CompositeTypes"]["pokemon_stats"]
      }
      search_pokemon_by_type: {
        Args: {
          type1: Database["public"]["Enums"]["pokemon_type"]
          type2?: Database["public"]["Enums"]["pokemon_type"]
        }
        Returns: Database["public"]["Tables"]["pokemon_species"]["Row"][]
      }
    }
    Enums: {
      battle_terrain: "normal" | "electric" | "grassy" | "misty" | "psychic"
      evolution_method: "level_up" | "trade" | "item" | "friendship" | "time_of_day" | "location" | "special"
      move_category: "physical" | "special" | "status"
      pokemon_nature: "hardy" | "lonely" | "brave" | "adamant" | "naughty" | "bold" | "docile" | "relaxed" | "impish" | "lax" | "timid" | "hasty" | "serious" | "jolly" | "naive" | "modest" | "mild" | "quiet" | "bashful" | "rash" | "calm" | "gentle" | "sassy" | "careful" | "quirky"
      pokemon_type: "normal" | "fire" | "water" | "electric" | "grass" | "ice" | "fighting" | "poison" | "ground" | "flying" | "psychic" | "bug" | "rock" | "ghost" | "dragon" | "dark" | "steel" | "fairy"
      status_condition: "none" | "burned" | "frozen" | "paralyzed" | "poisoned" | "badly_poisoned" | "asleep"
      weather_condition: "clear" | "sunny" | "rain" | "sandstorm" | "hail" | "snow" | "fog"
    }
    CompositeTypes: {
      geo_location: {
        latitude: number | null
        longitude: number | null
        altitude: number | null
      }
      pokemon_stats: {
        hp: number | null
        attack: number | null
        defense: number | null
        special_attack: number | null
        special_defense: number | null
        speed: number | null
      }
    }
  }
}

type PublicSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] &
        PublicSchema["Views"])
    ? (PublicSchema["Tables"] &
        PublicSchema["Views"])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
    ? PublicSchema["Enums"][PublicEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof PublicSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof PublicSchema["CompositeTypes"]
    ? PublicSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  "public": {
    Enums: {
      "battle_terrain": ["normal", "electric", "grassy", "misty", "psychic"],
      "evolution_method": ["level_up", "trade", "item", "friendship", "time_of_day", "location", "special"],
      "move_category": ["physical", "special", "status"],
      "pokemon_nature": ["hardy", "lonely", "brave", "adamant", "naughty", "bold", "docile", "relaxed", "impish", "lax", "timid", "hasty", "serious", "jolly", "naive", "modest", "mild", "quiet", "bashful", "rash", "calm", "gentle", "sassy", "careful", "quirky"],
      "pokemon_type": ["normal", "fire", "water", "electric", "grass", "ice", "fighting", "poison", "ground", "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy"],
      "status_condition": ["none", "burned", "frozen", "paralyzed", "poisoned", "badly_poisoned", "asleep"],
      "weather_condition": ["clear", "sunny", "rain", "sandstorm", "hail", "snow", "fog"],
    },
  },
} as const
