// Generated by pg-meta generate types go
// This is an example output from the Pokemon schema

package database

// =============================================================================
// TABLE STRUCTS
// =============================================================================

type PublicAbilitiesSelect struct {
	Id                   int32       `json:"id"`
	Name                 string      `json:"name"`
	Description          string      `json:"description"`
	IsHidden             *bool       `json:"is_hidden"`
	GenerationIntroduced int32       `json:"generation_introduced"`
	CreatedAt            *string     `json:"created_at"`
}

type PublicAbilitiesInsert struct {
	Id                   *int32      `json:"id"`
	Name                 string      `json:"name"`
	Description          string      `json:"description"`
	IsHidden             *bool       `json:"is_hidden"`
	GenerationIntroduced *int32      `json:"generation_introduced"`
	CreatedAt            *string     `json:"created_at"`
}

type PublicAbilitiesUpdate struct {
	Id                   *int32      `json:"id"`
	Name                 *string     `json:"name"`
	Description          *string     `json:"description"`
	IsHidden             *bool       `json:"is_hidden"`
	GenerationIntroduced *int32      `json:"generation_introduced"`
	CreatedAt            *string     `json:"created_at"`
}

type PublicBattleLogsSelect struct {
	Id             int32       `json:"id"`
	BattleId       string      `json:"battle_id"`
	Turn           int32       `json:"turn"`
	ActionOrder    int32       `json:"action_order"`
	ActorTrainerId string      `json:"actor_trainer_id"`
	ActionType     string      `json:"action_type"`
	ActionDetails  interface{} `json:"action_details"`
	Result         interface{} `json:"result"`
	CreatedAt      *string     `json:"created_at"`
}

type PublicBattleLogsInsert struct {
	Id             *int32      `json:"id"`
	BattleId       string      `json:"battle_id"`
	Turn           int32       `json:"turn"`
	ActionOrder    int32       `json:"action_order"`
	ActorTrainerId string      `json:"actor_trainer_id"`
	ActionType     string      `json:"action_type"`
	ActionDetails  interface{} `json:"action_details"`
	Result         interface{} `json:"result"`
	CreatedAt      *string     `json:"created_at"`
}

type PublicBattleLogsUpdate struct {
	Id             *int32      `json:"id"`
	BattleId       *string     `json:"battle_id"`
	Turn           *int32      `json:"turn"`
	ActionOrder    *int32      `json:"action_order"`
	ActorTrainerId *string     `json:"actor_trainer_id"`
	ActionType     *string     `json:"action_type"`
	ActionDetails  interface{} `json:"action_details"`
	Result         interface{} `json:"result"`
	CreatedAt      *string     `json:"created_at"`
}

type PublicBattlesSelect struct {
	Id         string      `json:"id"`
	Format     string      `json:"format"`
	Terrain    *string     `json:"terrain"`
	Weather    *string     `json:"weather"`
	Trainer1Id string      `json:"trainer1_id"`
	Trainer2Id string      `json:"trainer2_id"`
	WinnerId   *string     `json:"winner_id"`
	StartedAt  *string     `json:"started_at"`
	EndedAt    *string     `json:"ended_at"`
	Turns      *int32      `json:"turns"`
	IsRanked   *bool       `json:"is_ranked"`
	ReplayData interface{} `json:"replay_data"`
}

type PublicBattlesInsert struct {
	Id         *string     `json:"id"`
	Format     string      `json:"format"`
	Terrain    *string     `json:"terrain"`
	Weather    *string     `json:"weather"`
	Trainer1Id string      `json:"trainer1_id"`
	Trainer2Id string      `json:"trainer2_id"`
	WinnerId   *string     `json:"winner_id"`
	StartedAt  *string     `json:"started_at"`
	EndedAt    *string     `json:"ended_at"`
	Turns      *int32      `json:"turns"`
	IsRanked   *bool       `json:"is_ranked"`
	ReplayData interface{} `json:"replay_data"`
}

type PublicBattlesUpdate struct {
	Id         *string     `json:"id"`
	Format     *string     `json:"format"`
	Terrain    *string     `json:"terrain"`
	Weather    *string     `json:"weather"`
	Trainer1Id *string     `json:"trainer1_id"`
	Trainer2Id *string     `json:"trainer2_id"`
	WinnerId   *string     `json:"winner_id"`
	StartedAt  *string     `json:"started_at"`
	EndedAt    *string     `json:"ended_at"`
	Turns      *int32      `json:"turns"`
	IsRanked   *bool       `json:"is_ranked"`
	ReplayData interface{} `json:"replay_data"`
}

type PublicMovesSelect struct {
	Id                   int32       `json:"id"`
	Name                 string      `json:"name"`
	MoveType             string      `json:"move_type"`
	Category             string      `json:"category"`
	Power                *int32      `json:"power"`
	Accuracy             *int32      `json:"accuracy"`
	Pp                   int32       `json:"pp"`
	Priority             int32       `json:"priority"`
	Target               string      `json:"target"`
	MakesContact         *bool       `json:"makes_contact"`
	EffectDescription    *string     `json:"effect_description"`
	EffectChance         *int32      `json:"effect_chance"`
	StatusInflicted      *string     `json:"status_inflicted"`
	StatChanges          interface{} `json:"stat_changes"`
	GenerationIntroduced int32       `json:"generation_introduced"`
	IsZMove              *bool       `json:"is_z_move"`
	IsMaxMove            *bool       `json:"is_max_move"`
	CreatedAt            *string     `json:"created_at"`
}

type PublicMovesInsert struct {
	Id                   *int32      `json:"id"`
	Name                 string      `json:"name"`
	MoveType             string      `json:"move_type"`
	Category             string      `json:"category"`
	Power                *int32      `json:"power"`
	Accuracy             *int32      `json:"accuracy"`
	Pp                   int32       `json:"pp"`
	Priority             *int32      `json:"priority"`
	Target               string      `json:"target"`
	MakesContact         *bool       `json:"makes_contact"`
	EffectDescription    *string     `json:"effect_description"`
	EffectChance         *int32      `json:"effect_chance"`
	StatusInflicted      *string     `json:"status_inflicted"`
	StatChanges          interface{} `json:"stat_changes"`
	GenerationIntroduced *int32      `json:"generation_introduced"`
	IsZMove              *bool       `json:"is_z_move"`
	IsMaxMove            *bool       `json:"is_max_move"`
	CreatedAt            *string     `json:"created_at"`
}

type PublicMovesUpdate struct {
	Id                   *int32      `json:"id"`
	Name                 *string     `json:"name"`
	MoveType             *string     `json:"move_type"`
	Category             *string     `json:"category"`
	Power                *int32      `json:"power"`
	Accuracy             *int32      `json:"accuracy"`
	Pp                   *int32      `json:"pp"`
	Priority             *int32      `json:"priority"`
	Target               *string     `json:"target"`
	MakesContact         *bool       `json:"makes_contact"`
	EffectDescription    *string     `json:"effect_description"`
	EffectChance         *int32      `json:"effect_chance"`
	StatusInflicted      *string     `json:"status_inflicted"`
	StatChanges          interface{} `json:"stat_changes"`
	GenerationIntroduced *int32      `json:"generation_introduced"`
	IsZMove              *bool       `json:"is_z_move"`
	IsMaxMove            *bool       `json:"is_max_move"`
	CreatedAt            *string     `json:"created_at"`
}

type PublicPokemonSelect struct {
	Id                 string                   `json:"id"`
	SpeciesId          int32                    `json:"species_id"`
	TrainerId          *string                  `json:"trainer_id"`
	Nickname           *string                  `json:"nickname"`
	Level              int32                    `json:"level"`
	Experience         int32                    `json:"experience"`
	Nature             string                   `json:"nature"`
	AbilityId          int32                    `json:"ability_id"`
	Gender             *string                  `json:"gender"`
	IsShiny            *bool                    `json:"is_shiny"`
	IndividualValues   map[string]interface{}   `json:"individual_values"`
	EffortValues       map[string]interface{}   `json:"effort_values"`
	CurrentHp          int32                    `json:"current_hp"`
	Status             *string                  `json:"status"`
	Happiness          int32                    `json:"happiness"`
	HeldItem           *string                  `json:"held_item"`
	PokeballType       *string                  `json:"pokeball_type"`
	OriginalTrainerId  *string                  `json:"original_trainer_id"`
	CaughtAt           *string                  `json:"caught_at"`
	CaughtLocationId   *int32                   `json:"caught_location_id"`
	CaughtLevel        *int32                   `json:"caught_level"`
	IsEgg              *bool                    `json:"is_egg"`
	EggCyclesRemaining *int32                   `json:"egg_cycles_remaining"`
	FormId             *int32                   `json:"form_id"`
	DynamaxLevel       *int32                   `json:"dynamax_level"`
	CanGigantamax      *bool                    `json:"can_gigantamax"`
	TeraType           *string                  `json:"tera_type"`
	CreatedAt          *string                  `json:"created_at"`
	UpdatedAt          *string                  `json:"updated_at"`
}

type PublicPokemonInsert struct {
	Id                 *string                  `json:"id"`
	SpeciesId          int32                    `json:"species_id"`
	TrainerId          *string                  `json:"trainer_id"`
	Nickname           *string                  `json:"nickname"`
	Level              *int32                   `json:"level"`
	Experience         *int32                   `json:"experience"`
	Nature             string                   `json:"nature"`
	AbilityId          int32                    `json:"ability_id"`
	Gender             *string                  `json:"gender"`
	IsShiny            *bool                    `json:"is_shiny"`
	IndividualValues   map[string]interface{}   `json:"individual_values"`
	EffortValues       map[string]interface{}   `json:"effort_values"`
	CurrentHp          int32                    `json:"current_hp"`
	Status             *string                  `json:"status"`
	Happiness          *int32                   `json:"happiness"`
	HeldItem           *string                  `json:"held_item"`
	PokeballType       *string                  `json:"pokeball_type"`
	OriginalTrainerId  *string                  `json:"original_trainer_id"`
	CaughtAt           *string                  `json:"caught_at"`
	CaughtLocationId   *int32                   `json:"caught_location_id"`
	CaughtLevel        *int32                   `json:"caught_level"`
	IsEgg              *bool                    `json:"is_egg"`
	EggCyclesRemaining *int32                   `json:"egg_cycles_remaining"`
	FormId             *int32                   `json:"form_id"`
	DynamaxLevel       *int32                   `json:"dynamax_level"`
	CanGigantamax      *bool                    `json:"can_gigantamax"`
	TeraType           *string                  `json:"tera_type"`
	CreatedAt          *string                  `json:"created_at"`
	UpdatedAt          *string                  `json:"updated_at"`
}

type PublicPokemonUpdate struct {
	Id                 *string                  `json:"id"`
	SpeciesId          *int32                   `json:"species_id"`
	TrainerId          *string                  `json:"trainer_id"`
	Nickname           *string                  `json:"nickname"`
	Level              *int32                   `json:"level"`
	Experience         *int32                   `json:"experience"`
	Nature             *string                  `json:"nature"`
	AbilityId          *int32                   `json:"ability_id"`
	Gender             *string                  `json:"gender"`
	IsShiny            *bool                    `json:"is_shiny"`
	IndividualValues   map[string]interface{}   `json:"individual_values"`
	EffortValues       map[string]interface{}   `json:"effort_values"`
	CurrentHp          *int32                   `json:"current_hp"`
	Status             *string                  `json:"status"`
	Happiness          *int32                   `json:"happiness"`
	HeldItem           *string                  `json:"held_item"`
	PokeballType       *string                  `json:"pokeball_type"`
	OriginalTrainerId  *string                  `json:"original_trainer_id"`
	CaughtAt           *string                  `json:"caught_at"`
	CaughtLocationId   *int32                   `json:"caught_location_id"`
	CaughtLevel        *int32                   `json:"caught_level"`
	IsEgg              *bool                    `json:"is_egg"`
	EggCyclesRemaining *int32                   `json:"egg_cycles_remaining"`
	FormId             *int32                   `json:"form_id"`
	DynamaxLevel       *int32                   `json:"dynamax_level"`
	CanGigantamax      *bool                    `json:"can_gigantamax"`
	TeraType           *string                  `json:"tera_type"`
	CreatedAt          *string                  `json:"created_at"`
	UpdatedAt          *string                  `json:"updated_at"`
}

type PublicPokemonSpeciesSelect struct {
	Id               int32                  `json:"id"`
	NationalDexNumber int32                 `json:"national_dex_number"`
	Name             string                 `json:"name"`
	PrimaryType      string                 `json:"primary_type"`
	SecondaryType    *string                `json:"secondary_type"`
	BaseStats        map[string]interface{} `json:"base_stats"`
	HeightCm         int32                  `json:"height_cm"`
	WeightGrams      int32                  `json:"weight_grams"`
	CatchRate        int32                  `json:"catch_rate"`
	BaseExperience   int32                  `json:"base_experience"`
	BaseHappiness    int32                  `json:"base_happiness"`
	GrowthRate       string                 `json:"growth_rate"`
	EggGroups        []string               `json:"egg_groups"`
	GenderRatio      *float64               `json:"gender_ratio"`
	EggCycles        int32                  `json:"egg_cycles"`
	IsLegendary      *bool                  `json:"is_legendary"`
	IsMythical       *bool                  `json:"is_mythical"`
	IsBaby           *bool                  `json:"is_baby"`
	Generation       int32                  `json:"generation"`
	Description      *string                `json:"description"`
	CreatedAt        *string                `json:"created_at"`
	UpdatedAt        *string                `json:"updated_at"`
}

type PublicPokemonSpeciesInsert struct {
	Id               *int32                 `json:"id"`
	NationalDexNumber int32                 `json:"national_dex_number"`
	Name             string                 `json:"name"`
	PrimaryType      string                 `json:"primary_type"`
	SecondaryType    *string                `json:"secondary_type"`
	BaseStats        map[string]interface{} `json:"base_stats"`
	HeightCm         int32                  `json:"height_cm"`
	WeightGrams      int32                  `json:"weight_grams"`
	CatchRate        int32                  `json:"catch_rate"`
	BaseExperience   int32                  `json:"base_experience"`
	BaseHappiness    *int32                 `json:"base_happiness"`
	GrowthRate       string                 `json:"growth_rate"`
	EggGroups        []string               `json:"egg_groups"`
	GenderRatio      *float64               `json:"gender_ratio"`
	EggCycles        *int32                 `json:"egg_cycles"`
	IsLegendary      *bool                  `json:"is_legendary"`
	IsMythical       *bool                  `json:"is_mythical"`
	IsBaby           *bool                  `json:"is_baby"`
	Generation       int32                  `json:"generation"`
	Description      *string                `json:"description"`
	CreatedAt        *string                `json:"created_at"`
	UpdatedAt        *string                `json:"updated_at"`
}

type PublicPokemonSpeciesUpdate struct {
	Id               *int32                 `json:"id"`
	NationalDexNumber *int32                `json:"national_dex_number"`
	Name             *string                `json:"name"`
	PrimaryType      *string                `json:"primary_type"`
	SecondaryType    *string                `json:"secondary_type"`
	BaseStats        map[string]interface{} `json:"base_stats"`
	HeightCm         *int32                 `json:"height_cm"`
	WeightGrams      *int32                 `json:"weight_grams"`
	CatchRate        *int32                 `json:"catch_rate"`
	BaseExperience   *int32                 `json:"base_experience"`
	BaseHappiness    *int32                 `json:"base_happiness"`
	GrowthRate       *string                `json:"growth_rate"`
	EggGroups        []string               `json:"egg_groups"`
	GenderRatio      *float64               `json:"gender_ratio"`
	EggCycles        *int32                 `json:"egg_cycles"`
	IsLegendary      *bool                  `json:"is_legendary"`
	IsMythical       *bool                  `json:"is_mythical"`
	IsBaby           *bool                  `json:"is_baby"`
	Generation       *int32                 `json:"generation"`
	Description      *string                `json:"description"`
	CreatedAt        *string                `json:"created_at"`
	UpdatedAt        *string                `json:"updated_at"`
}

type PublicRegionsSelect struct {
	Id          int32   `json:"id"`
	Name        string  `json:"name"`
	Generation  int32   `json:"generation"`
	Description *string `json:"description"`
	CreatedAt   *string `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
}

type PublicRegionsInsert struct {
	Id          *int32  `json:"id"`
	Name        string  `json:"name"`
	Generation  int32   `json:"generation"`
	Description *string `json:"description"`
	CreatedAt   *string `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
}

type PublicRegionsUpdate struct {
	Id          *int32  `json:"id"`
	Name        *string `json:"name"`
	Generation  *int32  `json:"generation"`
	Description *string `json:"description"`
	CreatedAt   *string `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
}

type PublicTrainersSelect struct {
	Id           string   `json:"id"`
	Username     string   `json:"username"`
	Email        string   `json:"email"`
	DisplayName  *string  `json:"display_name"`
	AvatarUrl    *string  `json:"avatar_url"`
	HomeRegionId *int32   `json:"home_region_id"`
	TrainerClass *string  `json:"trainer_class"`
	BadgesEarned []int32  `json:"badges_earned"`
	PokedexSeen  *int32   `json:"pokedex_seen"`
	PokedexCaught *int32  `json:"pokedex_caught"`
	TotalBattles *int32   `json:"total_battles"`
	BattlesWon   *int32   `json:"battles_won"`
	Bio          *string  `json:"bio"`
	IsVerified   *bool    `json:"is_verified"`
	IsChampion   *bool    `json:"is_champion"`
	CreatedAt    *string  `json:"created_at"`
	UpdatedAt    *string  `json:"updated_at"`
	LastActiveAt *string  `json:"last_active_at"`
}

type PublicTrainersInsert struct {
	Id           *string  `json:"id"`
	Username     string   `json:"username"`
	Email        string   `json:"email"`
	DisplayName  *string  `json:"display_name"`
	AvatarUrl    *string  `json:"avatar_url"`
	HomeRegionId *int32   `json:"home_region_id"`
	TrainerClass *string  `json:"trainer_class"`
	BadgesEarned []int32  `json:"badges_earned"`
	PokedexSeen  *int32   `json:"pokedex_seen"`
	PokedexCaught *int32  `json:"pokedex_caught"`
	TotalBattles *int32   `json:"total_battles"`
	BattlesWon   *int32   `json:"battles_won"`
	Bio          *string  `json:"bio"`
	IsVerified   *bool    `json:"is_verified"`
	IsChampion   *bool    `json:"is_champion"`
	CreatedAt    *string  `json:"created_at"`
	UpdatedAt    *string  `json:"updated_at"`
	LastActiveAt *string  `json:"last_active_at"`
}

type PublicTrainersUpdate struct {
	Id           *string  `json:"id"`
	Username     *string  `json:"username"`
	Email        *string  `json:"email"`
	DisplayName  *string  `json:"display_name"`
	AvatarUrl    *string  `json:"avatar_url"`
	HomeRegionId *int32   `json:"home_region_id"`
	TrainerClass *string  `json:"trainer_class"`
	BadgesEarned []int32  `json:"badges_earned"`
	PokedexSeen  *int32   `json:"pokedex_seen"`
	PokedexCaught *int32  `json:"pokedex_caught"`
	TotalBattles *int32   `json:"total_battles"`
	BattlesWon   *int32   `json:"battles_won"`
	Bio          *string  `json:"bio"`
	IsVerified   *bool    `json:"is_verified"`
	IsChampion   *bool    `json:"is_champion"`
	CreatedAt    *string  `json:"created_at"`
	UpdatedAt    *string  `json:"updated_at"`
	LastActiveAt *string  `json:"last_active_at"`
}

type PublicTeamsSelect struct {
	Id          string  `json:"id"`
	TrainerId   string  `json:"trainer_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsActive    *bool   `json:"is_active"`
	Format      *string `json:"format"`
	CreatedAt   *string `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
}

type PublicTeamsInsert struct {
	Id          *string `json:"id"`
	TrainerId   string  `json:"trainer_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsActive    *bool   `json:"is_active"`
	Format      *string `json:"format"`
	CreatedAt   *string `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
}

type PublicTeamsUpdate struct {
	Id          *string `json:"id"`
	TrainerId   *string `json:"trainer_id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	IsActive    *bool   `json:"is_active"`
	Format      *string `json:"format"`
	CreatedAt   *string `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
}

// =============================================================================
// VIEW STRUCTS (SELECT ONLY)
// =============================================================================

type PublicTrainerStatsSelect struct {
	Id            *string  `json:"id"`
	Username      *string  `json:"username"`
	DisplayName   *string  `json:"display_name"`
	TrainerClass  *string  `json:"trainer_class"`
	TotalBattles  *int32   `json:"total_battles"`
	BattlesWon    *int32   `json:"battles_won"`
	WinRate       *float64 `json:"win_rate"`
	PokedexCaught *int32   `json:"pokedex_caught"`
	TotalPokemon  *int64   `json:"total_pokemon"`
	ShinyCount    *int64   `json:"shiny_count"`
	BadgeCount    *int32   `json:"badge_count"`
	IsChampion    *bool    `json:"is_champion"`
	MemberSince   *string  `json:"member_since"`
}

type PublicPokemonFullSelect struct {
	Id               *string `json:"id"`
	Nickname         *string `json:"nickname"`
	SpeciesName      *string `json:"species_name"`
	NationalDexNumber *int32 `json:"national_dex_number"`
	PrimaryType      *string `json:"primary_type"`
	SecondaryType    *string `json:"secondary_type"`
	Level            *int32  `json:"level"`
	Nature           *string `json:"nature"`
	AbilityName      *string `json:"ability_name"`
	Gender           *string `json:"gender"`
	IsShiny          *bool   `json:"is_shiny"`
	CurrentHp        *int32  `json:"current_hp"`
	Status           *string `json:"status"`
	Happiness        *int32  `json:"happiness"`
	HeldItem         *string `json:"held_item"`
	TrainerUsername  *string `json:"trainer_username"`
	CaughtLocation   *string `json:"caught_location"`
	CaughtRegion     *string `json:"caught_region"`
	CaughtAt         *string `json:"caught_at"`
}

type PublicTypeMatchupsSelect struct {
	Id            *int32  `json:"id"`
	Name          *string `json:"name"`
	PrimaryType   *string `json:"primary_type"`
	SecondaryType *string `json:"secondary_type"`
	BaseStatTotal *int64  `json:"base_stat_total"`
	IsLegendary   *bool   `json:"is_legendary"`
	IsMythical    *bool   `json:"is_mythical"`
}

// =============================================================================
// COMPOSITE TYPES
// =============================================================================

type PublicPokemonStats struct {
	Hp             int32 `json:"hp"`
	Attack         int32 `json:"attack"`
	Defense        int32 `json:"defense"`
	SpecialAttack  int32 `json:"special_attack"`
	SpecialDefense int32 `json:"special_defense"`
	Speed          int32 `json:"speed"`
}

type PublicGeoLocation struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Altitude  int32   `json:"altitude"`
}
